import type { OnboardingQuestion } from "@shared/schema";

export const ONBOARDING_QUESTIONS: OnboardingQuestion[] = [
  // STUDY HABITS (Questions 1-4)
  {
    id: "study_environment",
    questionEn: "Where do you usually study?",
    questionAf: "Waar studeer jy gewoonlik?",
    type: "single",
    options: [
      { value: "quiet_room", labelEn: "Quiet room alone", labelAf: "Op my eie in 'n stil kamer" },
      { value: "with_music", labelEn: "With music or background noise", labelAf: "Met musiek of iets op die agtergrond" },
      { value: "library", labelEn: "Library or study group", labelAf: "In die biblioteek of saam met vriende" },
      { value: "anywhere", labelEn: "Anywhere - I can adapt", labelAf: "Oral — ek kan aanpas by enige plek" },
    ],
  },
  {
    id: "study_time",
    questionEn: "When do you feel most focused for studying?",
    questionAf: "Wanneer is jy die meeste in die zone vir studeer?",
    type: "single",
    options: [
      { value: "morning", labelEn: "Early morning (5am-9am)", labelAf: "Vroeg in die oggend (5vm–9vm)" },
      { value: "afternoon", labelEn: "Afternoon (12pm-5pm)", labelAf: "In die middag (12nm–5nm)" },
      { value: "evening", labelEn: "Evening (5pm-9pm)", labelAf: "Saans (5nm–9nm)" },
      { value: "night", labelEn: "Late night (9pm+)", labelAf: "Laat in die nag (9nm en later)" },
    ],
  },
  {
    id: "study_frequency",
    questionEn: "How often do you study outside of class?",
    questionAf: "Hoe gereeld sit jy en studeer buite skool?",
    type: "single",
    options: [
      { value: "daily", labelEn: "Every day", labelAf: "Elke dag — dis my gewoonte" },
      { value: "few_times", labelEn: "A few times a week", labelAf: "Paar keer in die week" },
      { value: "weekends", labelEn: "Mostly weekends", labelAf: "Hoofsaaklik naweke" },
      { value: "before_tests", labelEn: "Only before tests", labelAf: "Net wanneer 'n toets of eksamen naby is" },
    ],
  },
  {
    id: "note_taking",
    questionEn: "How do you take notes?",
    questionAf: "Hoe maak jy jou notas?",
    type: "single",
    options: [
      { value: "detailed", labelEn: "Detailed written notes", labelAf: "Lekker uitgebreide, geskrewe notas" },
      { value: "summaries", labelEn: "Short summaries and keywords", labelAf: "Kort opsommings en sleutelwoorde" },
      { value: "diagrams", labelEn: "Mind maps and diagrams", labelAf: "Breinkaarte en tekeninge" },
      { value: "none", labelEn: "I don't take notes", labelAf: "Ek maak nie regtig notas nie" },
    ],
  },

  // FOCUS SPAN (Questions 5-8)
  {
    id: "focus_duration",
    questionEn: "How long can you focus before needing a break?",
    questionAf: "Hoe lank hou jy dit vol voor jy 'n blaaskans nodig het?",
    type: "slider",
    min: 15,
    max: 120,
    step: 15,
  },
  {
    id: "distraction_level",
    questionEn: "How easily do you get distracted while studying?",
    questionAf: "Raak jy maklik afgelei as jy probeer studeer?",
    type: "single",
    options: [
      { value: "rarely", labelEn: "Rarely - I stay focused", labelAf: "Selde — ek kan myself fokus hou" },
      { value: "sometimes", labelEn: "Sometimes, but I recover quickly", labelAf: "Soms, maar ek kom vinnig terug op koers" },
      { value: "often", labelEn: "Often - it's a struggle", labelAf: "Dikwels — dit vat moeite om gefokus te bly" },
      { value: "always", labelEn: "Very easily distracted", labelAf: "Enige iets trek my aandag weg" },
    ],
  },
  {
    id: "phone_usage",
    questionEn: "What do you do with your phone while studying?",
    questionAf: "Wat maak jy met jou foon as jy studeer?",
    type: "single",
    options: [
      { value: "off", labelEn: "Turn it off or leave in another room", labelAf: "Ek skakel dit af of los dit in 'n ander kamer" },
      { value: "silent", labelEn: "Put on silent nearby", labelAf: "Op stil, maar hy's nog naby my" },
      { value: "check", labelEn: "Check it occasionally", labelAf: "Ek kyk nou en dan wat aangaan" },
      { value: "always", labelEn: "Always have it with me", labelAf: "Dis altyd in my hand — eerlik!" },
    ],
  },
  {
    id: "break_activity",
    questionEn: "What do you do during study breaks?",
    questionAf: "Wat doen jy as jy 'n blaaskans neem tussen studeer?",
    type: "single",
    options: [
      { value: "physical", labelEn: "Physical activity (walk, stretch)", labelAf: "Stap of rek — iets fisies" },
      { value: "social", labelEn: "Social media or chat", labelAf: "Sosiale media of WhatsApp" },
      { value: "snack", labelEn: "Snack or drink", labelAf: "Iets eet of drink" },
      { value: "continue", labelEn: "I don't take breaks", labelAf: "Ek vat nie regtig pouses nie" },
    ],
  },

  // PRACTICE PREFERENCE (Questions 9-12)
  {
    id: "learning_style",
    questionEn: "How do you learn best?",
    questionAf: "Hoe snap jy goeters die beste?",
    type: "single",
    options: [
      { value: "visual", labelEn: "Visual Learner - diagrams and videos", labelAf: "Deur te kyk — diagramme en video's" },
      { value: "auditory", labelEn: "Auditory Learner - listening and discussions", labelAf: "Deur te luister en te gesels oor dit" },
      { value: "reading", labelEn: "Reading/Writing - textbooks and notes", labelAf: "Deur te lees en self notas te skryf" },
      { value: "kinesthetic", labelEn: "Kinesthetic Learner - hands-on practice", labelAf: "Deur dit self te probeer en te oefen" },
    ],
  },
  {
    id: "practice_method",
    questionEn: "How do you prefer to practice for exams?",
    questionAf: "Hoe oefen jy die liefste vir eksamens?",
    type: "single",
    options: [
      { value: "past_papers", labelEn: "Simulated practice exams", labelAf: "Oefenvraestelle doen soos in 'n regte eksamen" },
      { value: "textbook", labelEn: "Textbook exercises", labelAf: "Handboek oefeninge deurdoen" },
      { value: "flashcards", labelEn: "Flashcards and quizzes", labelAf: "Flitskaarte en vinnige vasvrae" },
      { value: "teaching", labelEn: "Teaching others", labelAf: "Dit vir iemand anders verduidelik" },
    ],
  },
  {
    id: "mistake_response",
    questionEn: "When you get a question wrong, what do you do?",
    questionAf: "As jy 'n vraag verkeerd het, wat doen jy dan?",
    type: "single",
    options: [
      { value: "analyze", labelEn: "Carefully analyze the mistake", labelAf: "Ek kyk noukeurig waar ek gemors het" },
      { value: "redo", labelEn: "Redo until I get it right", labelAf: "Ek doen dit oor en oor tot ek dit reg het" },
      { value: "ask", labelEn: "Ask someone to explain", labelAf: "Ek vra iemand om dit vir my te verduidelik" },
      { value: "skip", labelEn: "Move on to the next question", labelAf: "Ek gaan aan — ek sal later kyk" },
    ],
  },
  {
    id: "help_seeking",
    questionEn: "When you're stuck on a concept, what do you do first?",
    questionAf: "As jy vashaak op iets, wat is die eerste ding wat jy doen?",
    type: "single",
    options: [
      { value: "teacher", labelEn: "Ask my teacher", labelAf: "Ek vra my onderwyser" },
      { value: "classmate", labelEn: "Ask a classmate", labelAf: "Ek vra 'n vriend of klasmaat" },
      { value: "internet", labelEn: "Search online", labelAf: "Ek soek dit op aanlyn" },
      { value: "struggle", labelEn: "Keep trying on my own", labelAf: "Ek bly probeer op my eie tot ek dit kry" },
    ],
  },

  // EXAM STRESS (Questions 13-15)
  {
    id: "exam_anxiety",
    questionEn: "How do you feel before an exam?",
    questionAf: "Hoe voel jy die dag voor 'n groot eksamen?",
    type: "single",
    options: [
      { value: "calm", labelEn: "Calm and confident", labelAf: "Kalm en selfversekerd — ek's reg" },
      { value: "nervous", labelEn: "A bit nervous but manageable", labelAf: "Bietjie senuweeagtig maar ek hou dit bymekaar" },
      { value: "stressed", labelEn: "Very stressed and anxious", labelAf: "Baie gespanne en bekommerd" },
      { value: "panic", labelEn: "I tend to panic", labelAf: "Ek raak maklik in 'n paniek" },
    ],
  },
  {
    id: "stress_management",
    questionEn: "How do you manage exam stress?",
    questionAf: "Hoe hanteer jy eksamenstres?",
    type: "single",
    options: [
      { value: "exercise", labelEn: "Exercise or physical activity", labelAf: "Ek sport of doen iets fisies" },
      { value: "talk", labelEn: "Talk to friends or family", labelAf: "Ek gesels met vriende of my familie" },
      { value: "prepare", labelEn: "Study more to feel prepared", labelAf: "Ek studeer meer sodat ek meer voorbereid voel" },
      { value: "nothing", labelEn: "I struggle to manage it", labelAf: "Ek sukkel eerlik gesê om dit te hanteer" },
    ],
  },
  {
    id: "exam_performance",
    questionEn: "Do you usually perform better or worse than expected in exams?",
    questionAf: "Presteer jy gewoonlik soos jy verwag het, of kry jy verrassings?",
    type: "single",
    options: [
      { value: "better", labelEn: "Better than expected", labelAf: "Beter as wat ek gedink het" },
      { value: "same", labelEn: "About what I expected", labelAf: "Min of meer soos ek verwag het" },
      { value: "worse", labelEn: "Worse than expected", labelAf: "Slegter as wat ek gehoop het" },
      { value: "varies", labelEn: "It varies a lot", labelAf: "Dis elke keer anders — nooit seker nie" },
    ],
  },

  // PLANNING VS PROCRASTINATION (Questions 16-18)
  {
    id: "planning_style",
    questionEn: "How do you plan your study time?",
    questionAf: "Hoe beplan jy wanneer en wat jy gaan studeer?",
    type: "single",
    options: [
      { value: "schedule", labelEn: "Detailed timetable and schedule", labelAf: "Ek het 'n gedetailleerde rooster wat ek volg" },
      { value: "loose", labelEn: "Rough plan, flexible", labelAf: "Rowwe plan — buigsaam na gelang van hoe dit gaan" },
      { value: "mood", labelEn: "I study when I feel like it", labelAf: "Ek studeer as ek lus het" },
      { value: "deadline", labelEn: "Only when deadlines approach", labelAf: "Net as eksamens of sperdatums naby kom" },
    ],
  },
  {
    id: "procrastination",
    questionEn: "How often do you procrastinate on studying?",
    questionAf: "Hoe dikwels stel jy studeer uit vir later?",
    type: "single",
    options: [
      { value: "never", labelEn: "Almost never", labelAf: "Amper nooit — ek doen dit net" },
      { value: "sometimes", labelEn: "Sometimes", labelAf: "Soms gebeur dit" },
      { value: "often", labelEn: "Often", labelAf: "Redelik gereeld, ja" },
      { value: "always", labelEn: "Very often - it's my weakness", labelAf: "Baie gereeld — dis my grootste uitdaging" },
    ],
  },
  {
    id: "goals",
    questionEn: "What are your matric goals?",
    questionAf: "Wat wil jy hierdie jaar in matriek bereik?",
    type: "multiple",
    options: [
      { value: "bachelor_pass", labelEn: "Bachelor's pass", labelAf: "'n Baccalaureuspas kry" },
      { value: "distinctions", labelEn: "Achieve distinctions", labelAf: "Onderskeidings in my vakke" },
      { value: "university", labelEn: "Get into university", labelAf: "Universiteitstoelating kry" },
      { value: "bursary", labelEn: "Qualify for bursary", labelAf: "Vir 'n beurs kwalifiseer" },
      { value: "improve_marks", labelEn: "Improve my marks", labelAf: "My punte verbeter van verlede jaar" },
    ],
  },
];

// Trait calculation based on answers
export interface StudyTraits {
  studyHabits: "excellent" | "good" | "developing" | "needs_work";
  focusLevel: "high" | "moderate" | "low" | "very_low";
  practiceStyle: "active" | "passive" | "mixed";
  stressResilience: "high" | "moderate" | "low";
  planningAbility: "strong" | "moderate" | "weak";
}

export const GRADE_12_SUBJECTS = [
  // Mathematics
  { name: "Mathematics", nameAfrikaans: "Wiskunde", code: "MATH", category: "Mathematics" },
  { name: "Mathematical Literacy", nameAfrikaans: "Wiskundige Geletterdheid", code: "MATL", category: "Mathematics" },
  { name: "Technical Mathematics", nameAfrikaans: "Tegniese Wiskunde", code: "TMATH", category: "Mathematics" },
  // Sciences
  { name: "Physical Sciences", nameAfrikaans: "Fisiese Wetenskappe", code: "PHYS", category: "Sciences" },
  { name: "Life Sciences", nameAfrikaans: "Lewenswetenskappe", code: "LIFE", category: "Sciences" },
  { name: "Agricultural Sciences", nameAfrikaans: "Landbouwetenskappe", code: "AGR", category: "Sciences" },
  { name: "Technical Sciences", nameAfrikaans: "Tegniese Wetenskappe", code: "TSCI", category: "Sciences" },
  // Commerce & Management
  { name: "Accounting", nameAfrikaans: "Rekeningkunde", code: "ACC", category: "Commerce" },
  { name: "Business Studies", nameAfrikaans: "Besigheidstudies", code: "BUS", category: "Commerce" },
  { name: "Economics", nameAfrikaans: "Ekonomie", code: "ECO", category: "Commerce" },
  // Humanities & Social Sciences
  { name: "History", nameAfrikaans: "Geskiedenis", code: "HIS", category: "Humanities" },
  { name: "Geography", nameAfrikaans: "Geografie", code: "GEO", category: "Humanities" },
  { name: "Religion Studies", nameAfrikaans: "Godsdiensstudies", code: "RELI", category: "Humanities" },
  { name: "Tourism", nameAfrikaans: "Toerisme", code: "TOUR", category: "Humanities" },
  // Languages
  { name: "English Home Language", nameAfrikaans: "Engels Huistaal", code: "ENGH", category: "Languages" },
  { name: "English First Additional Language", nameAfrikaans: "Engels Eerste Addisionele Taal", code: "ENGF", category: "Languages" },
  { name: "Afrikaans Home Language", nameAfrikaans: "Afrikaans Huistaal", code: "AFRH", category: "Languages" },
  { name: "Afrikaans First Additional Language", nameAfrikaans: "Afrikaans Eerste Addisionele Taal", code: "AFRF", category: "Languages" },
  // Creative & Expressive Arts
  { name: "Visual Arts", nameAfrikaans: "Visuele Kunste", code: "ART", category: "Arts" },
  { name: "Dramatic Arts", nameAfrikaans: "Dramatiese Kunste", code: "DRAMA", category: "Arts" },
  { name: "Dance Studies", nameAfrikaans: "Dansstudies", code: "DANCE", category: "Arts" },
  { name: "Music", nameAfrikaans: "Musiek", code: "MUSIC", category: "Arts" },
  { name: "Design", nameAfrikaans: "Ontwerp", code: "DESIGN", category: "Arts" },
  // Technology & Engineering
  { name: "Information Technology", nameAfrikaans: "Inligtingstegnologie", code: "IT", category: "Technical" },
  { name: "Computer Applications Technology", nameAfrikaans: "Rekenaartoepassingstegnologie", code: "CAT", category: "Technical" },
  { name: "Engineering Graphics and Design", nameAfrikaans: "Ingenieursgrafika en Ontwerp", code: "EGD", category: "Technical" },
  { name: "Civil Technology", nameAfrikaans: "Siviele Tegnologie", code: "CIVT", category: "Technical" },
  { name: "Electrical Technology", nameAfrikaans: "Elektriese Tegnologie", code: "ELEC", category: "Technical" },
  { name: "Mechanical Technology", nameAfrikaans: "Meganiese Tegnologie", code: "MECH", category: "Technical" },
  { name: "Digital Technology", nameAfrikaans: "Digitale Tegnologie", code: "DIGT", category: "Technical" },
  // Agriculture & Environment
  { name: "Agricultural Management Practices", nameAfrikaans: "Landboubestuurspraktyke", code: "AGRM", category: "Agriculture" },
  { name: "Agricultural Technology", nameAfrikaans: "Landboutegnologie", code: "AGRT", category: "Agriculture" },
  // Services & Consumer Studies
  { name: "Consumer Studies", nameAfrikaans: "Verbruikerstudies", code: "CON", category: "Services" },
  { name: "Hospitality Studies", nameAfrikaans: "Gasvryheidstudie", code: "HOSP", category: "Services" },
  // Life Orientation
  { name: "Life Orientation", nameAfrikaans: "Lewensoriëntering", code: "LO", category: "Life Orientation" },
  // African Official Languages — Home Language
  { name: "isiZulu Home Language", nameAfrikaans: "isiZulu Huistaal", code: "ZULH", category: "Languages" },
  { name: "isiXhosa Home Language", nameAfrikaans: "isiXhosa Huistaal", code: "XHOH", category: "Languages" },
  { name: "Sepedi Home Language", nameAfrikaans: "Sepedi Huistaal", code: "SEPH", category: "Languages" },
  { name: "Setswana Home Language", nameAfrikaans: "Setswana Huistaal", code: "SETH", category: "Languages" },
  { name: "Sesotho Home Language", nameAfrikaans: "Sesotho Huistaal", code: "SESH", category: "Languages" },
  { name: "Tshivenda Home Language", nameAfrikaans: "Tshivenda Huistaal", code: "TSHH", category: "Languages" },
  { name: "Xitsonga Home Language", nameAfrikaans: "Xitsonga Huistaal", code: "XITH", category: "Languages" },
  { name: "isiNdebele Home Language", nameAfrikaans: "isiNdebele Huistaal", code: "NDH", category: "Languages" },
  { name: "siSwati Home Language", nameAfrikaans: "siSwati Huistaal", code: "SWAH", category: "Languages" },
  // African Official Languages — First Additional Language
  { name: "isiZulu First Additional Language", nameAfrikaans: "isiZulu Eerste Addisionele Taal", code: "ZULF", category: "Languages" },
  { name: "isiXhosa First Additional Language", nameAfrikaans: "isiXhosa Eerste Addisionele Taal", code: "XHOF", category: "Languages" },
  { name: "Sepedi First Additional Language", nameAfrikaans: "Sepedi Eerste Addisionele Taal", code: "SEPF", category: "Languages" },
  { name: "Setswana First Additional Language", nameAfrikaans: "Setswana Eerste Addisionele Taal", code: "SETF", category: "Languages" },
  { name: "Sesotho First Additional Language", nameAfrikaans: "Sesotho Eerste Addisionele Taal", code: "SESF", category: "Languages" },
  { name: "Tshivenda First Additional Language", nameAfrikaans: "Tshivenda Eerste Addisionele Taal", code: "TSHF", category: "Languages" },
  { name: "Xitsonga First Additional Language", nameAfrikaans: "Xitsonga Eerste Addisionele Taal", code: "XITF", category: "Languages" },
  { name: "isiNdebele First Additional Language", nameAfrikaans: "isiNdebele Eerste Addisionele Taal", code: "NDF", category: "Languages" },
  { name: "siSwati First Additional Language", nameAfrikaans: "siSwati Eerste Addisionele Taal", code: "SWAF", category: "Languages" },
  // Sciences — Niche
  { name: "Marine Sciences", nameAfrikaans: "Mariene Wetenskappe", code: "MRSCI", category: "Sciences" },
];

export const SUBJECT_CATEGORIES = [
  { id: "Mathematics", labelEn: "Mathematics", labelAf: "Wiskunde" },
  { id: "Sciences", labelEn: "Sciences", labelAf: "Wetenskappe" },
  { id: "Commerce", labelEn: "Commerce & Management", labelAf: "Handel & Bestuur" },
  { id: "Humanities", labelEn: "Humanities & Social Sciences", labelAf: "Geesteswetenskappe" },
  { id: "Languages", labelEn: "Languages", labelAf: "Tale" },
  { id: "Arts", labelEn: "Creative & Expressive Arts", labelAf: "Kreatiewe Kunste" },
  { id: "Technical", labelEn: "Technology & Engineering", labelAf: "Tegnologie & Ingenieurswese" },
  { id: "Agriculture", labelEn: "Agriculture & Environment", labelAf: "Landbou & Omgewing" },
  { id: "Services", labelEn: "Services & Consumer Studies", labelAf: "Dienste & Verbruikerstudies" },
  { id: "Life Orientation", labelEn: "Life Orientation", labelAf: "Lewensoriëntering" },
];

// CAPS Curriculum Topics per Subject (Grade 12)
export const CAPS_TOPICS: Record<string, { name: string; nameAfrikaans: string; capsCode: string }[]> = {
  MATH: [
    { name: "Patterns, Sequences and Series", nameAfrikaans: "Patrone, Rye en Reekse", capsCode: "MATH-1" },
    { name: "Functions and Inverse Functions", nameAfrikaans: "Funksies en Inverse Funksies", capsCode: "MATH-2" },
    { name: "Exponential and Logarithmic Functions", nameAfrikaans: "Eksponensiële en Logaritmiese Funksies", capsCode: "MATH-3" },
    { name: "Finance, Growth and Decay", nameAfrikaans: "Finansies, Groei en Verval", capsCode: "MATH-4" },
    { name: "Trigonometry", nameAfrikaans: "Trigonometrie", capsCode: "MATH-5" },
    { name: "Polynomials", nameAfrikaans: "Polinome", capsCode: "MATH-6" },
    { name: "Differential Calculus", nameAfrikaans: "Differensiaalrekene", capsCode: "MATH-7" },
    { name: "Analytical Geometry", nameAfrikaans: "Analitiese Meetkunde", capsCode: "MATH-8" },
    { name: "Euclidean Geometry", nameAfrikaans: "Euklidiese Meetkunde", capsCode: "MATH-9" },
    { name: "Statistics", nameAfrikaans: "Statistiek", capsCode: "MATH-10" },
    { name: "Counting and Probability", nameAfrikaans: "Tel en Waarskynlikheid", capsCode: "MATH-11" },
  ],
  MATL: [
    { name: "Finance", nameAfrikaans: "Finansies", capsCode: "MATL-1" },
    { name: "Data Handling", nameAfrikaans: "Datahantering", capsCode: "MATL-2" },
    { name: "Measurement", nameAfrikaans: "Meting", capsCode: "MATL-3" },
    { name: "Maps and Plans", nameAfrikaans: "Kaarte en Planne", capsCode: "MATL-4" },
    { name: "Probability", nameAfrikaans: "Waarskynlikheid", capsCode: "MATL-5" },
  ],
  PHYS: [
    { name: "Momentum and Impulse", nameAfrikaans: "Momentum en Impuls", capsCode: "PHYS-1" },
    { name: "Vertical Projectile Motion", nameAfrikaans: "Vertikale Projektielbeweging", capsCode: "PHYS-2" },
    { name: "Organic Chemistry", nameAfrikaans: "Organiese Chemie", capsCode: "PHYS-3" },
    { name: "Work, Energy and Power", nameAfrikaans: "Arbeid, Energie en Drywing", capsCode: "PHYS-4" },
    { name: "Doppler Effect", nameAfrikaans: "Dopplereffek", capsCode: "PHYS-5" },
    { name: "Electric Circuits", nameAfrikaans: "Elektriese Stroombane", capsCode: "PHYS-6" },
    { name: "Electrodynamics", nameAfrikaans: "Elektrodinamika", capsCode: "PHYS-7" },
    { name: "Optical Phenomena", nameAfrikaans: "Optiese Verskynsels", capsCode: "PHYS-8" },
    { name: "Electrochemistry", nameAfrikaans: "Elektrochemie", capsCode: "PHYS-9" },
    { name: "Chemical Industry", nameAfrikaans: "Chemiese Nywerheid", capsCode: "PHYS-10" },
  ],
  LIFE: [
    { name: "DNA and RNA", nameAfrikaans: "DNA en RNA", capsCode: "LIFE-1" },
    { name: "Meiosis", nameAfrikaans: "Meiose", capsCode: "LIFE-2" },
    { name: "Reproduction in Vertebrates", nameAfrikaans: "Voortplanting by Gewerweldes", capsCode: "LIFE-3" },
    { name: "Human Reproduction", nameAfrikaans: "Menslike Voortplanting", capsCode: "LIFE-4" },
    { name: "Genetics and Inheritance", nameAfrikaans: "Genetika en Oorerwing", capsCode: "LIFE-5" },
    { name: "Evolution", nameAfrikaans: "Evolusie", capsCode: "LIFE-6" },
    { name: "Human Evolution", nameAfrikaans: "Menslike Evolusie", capsCode: "LIFE-7" },
    { name: "Human Nervous System", nameAfrikaans: "Menslike Senuweestelsel", capsCode: "LIFE-8" },
    { name: "Endocrine System", nameAfrikaans: "Endokriene Stelsel", capsCode: "LIFE-9" },
    { name: "Homeostasis", nameAfrikaans: "Homeostase", capsCode: "LIFE-10" },
  ],
  ACC: [
    { name: "Companies: Financial Statements", nameAfrikaans: "Maatskappye: Finansiële State", capsCode: "ACC-1" },
    { name: "Companies: Analysis and Interpretation", nameAfrikaans: "Maatskappye: Ontleding en Interpretasie", capsCode: "ACC-2" },
    { name: "Manufacturing", nameAfrikaans: "Vervaardiging", capsCode: "ACC-3" },
    { name: "Budgeting", nameAfrikaans: "Begrotings", capsCode: "ACC-4" },
    { name: "Inventory Valuation", nameAfrikaans: "Voorraadwaardasie", capsCode: "ACC-5" },
    { name: "Reconciliations", nameAfrikaans: "Rekonsiliasies", capsCode: "ACC-6" },
    { name: "Internal Control and Audit", nameAfrikaans: "Interne Beheer en Oudit", capsCode: "ACC-7" },
    { name: "Ethics and Governance", nameAfrikaans: "Etiek en Bestuur", capsCode: "ACC-8" },
  ],
  BUS: [
    { name: "Business Environments", nameAfrikaans: "Sake-omgewings", capsCode: "BUS-1" },
    { name: "Business Operations", nameAfrikaans: "Sake-bedrywighede", capsCode: "BUS-2" },
    { name: "Business Ventures", nameAfrikaans: "Sake-ondernemings", capsCode: "BUS-3" },
    { name: "Business Roles", nameAfrikaans: "Sake-rolle", capsCode: "BUS-4" },
    { name: "Human Resources", nameAfrikaans: "Menslike Hulpbronne", capsCode: "BUS-5" },
    { name: "Marketing", nameAfrikaans: "Bemarking", capsCode: "BUS-6" },
    { name: "Quality and Production", nameAfrikaans: "Kwaliteit en Produksie", capsCode: "BUS-7" },
    { name: "Ethics and Professionalism", nameAfrikaans: "Etiek en Professionalisme", capsCode: "BUS-8" },
  ],
  ECO: [
    { name: "Macroeconomics", nameAfrikaans: "Makro-ekonomie", capsCode: "ECO-1" },
    { name: "Microeconomics", nameAfrikaans: "Mikro-ekonomie", capsCode: "ECO-2" },
    { name: "Economic Pursuits", nameAfrikaans: "Ekonomiese Strewes", capsCode: "ECO-3" },
    { name: "Contemporary Economic Issues", nameAfrikaans: "Hedendaagse Ekonomiese Kwessies", capsCode: "ECO-4" },
    { name: "Economic Growth and Development", nameAfrikaans: "Ekonomiese Groei en Ontwikkeling", capsCode: "ECO-5" },
    { name: "Industrial Development", nameAfrikaans: "Nywerheidsontwikkeling", capsCode: "ECO-6" },
    { name: "Globalisation", nameAfrikaans: "Globalisering", capsCode: "ECO-7" },
    { name: "Protectionism and Free Trade", nameAfrikaans: "Proteksionisme en Vrye Handel", capsCode: "ECO-8" },
  ],
  GEO: [
    { name: "Climate and Weather", nameAfrikaans: "Klimaat en Weer", capsCode: "GEO-1" },
    { name: "Geomorphology", nameAfrikaans: "Geomorfologie", capsCode: "GEO-2" },
    { name: "Settlement Geography", nameAfrikaans: "Nedersettingsgeografie", capsCode: "GEO-3" },
    { name: "Economic Geography", nameAfrikaans: "Ekonomiese Geografie", capsCode: "GEO-4" },
    { name: "Mapwork and GIS", nameAfrikaans: "Kaartwerk en GIS", capsCode: "GEO-5" },
    { name: "Water Resources", nameAfrikaans: "Waterhulpbronne", capsCode: "GEO-6" },
  ],
  HIS: [
    { name: "Cold War", nameAfrikaans: "Koue Oorlog", capsCode: "HIS-1" },
    { name: "Civil Resistance 1970s-1980s", nameAfrikaans: "Burgerlike Weerstand 1970s–1980s", capsCode: "HIS-2" },
    { name: "End of Cold War and New World Order", nameAfrikaans: "Einde van die Koue Oorlog en Nuwe Wêreldorde", capsCode: "HIS-3" },
    { name: "Globalisation", nameAfrikaans: "Globalisering", capsCode: "HIS-4" },
    { name: "Independent Africa", nameAfrikaans: "Onafhanklike Afrika", capsCode: "HIS-5" },
    { name: "TRC and Coming to Terms with the Past", nameAfrikaans: "WVK en Afrekening met die Verlede", capsCode: "HIS-6" },
  ],
  ENGH: [
    { name: "Literature: Novel", nameAfrikaans: "Letterkunde: Roman", capsCode: "ENGH-1" },
    { name: "Literature: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "ENGH-2" },
    { name: "Literature: Poetry", nameAfrikaans: "Letterkunde: Poësie", capsCode: "ENGH-3" },
    { name: "Literature: Short Stories", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "ENGH-4" },
    { name: "Language Structures", nameAfrikaans: "Taalstrukture", capsCode: "ENGH-5" },
    { name: "Comprehension and Summary", nameAfrikaans: "Begrip en Opsomming", capsCode: "ENGH-6" },
    { name: "Essay Writing", nameAfrikaans: "Opstelskryf", capsCode: "ENGH-7" },
    { name: "Transactional Writing", nameAfrikaans: "Transaksionele Skryf", capsCode: "ENGH-8" },
  ],
  ENGF: [
    { name: "Literature: Novel", nameAfrikaans: "Letterkunde: Roman", capsCode: "ENGF-1" },
    { name: "Literature: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "ENGF-2" },
    { name: "Literature: Poetry", nameAfrikaans: "Letterkunde: Poësie", capsCode: "ENGF-3" },
    { name: "Literature: Short Stories", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "ENGF-4" },
    { name: "Language Structures", nameAfrikaans: "Taalstrukture", capsCode: "ENGF-5" },
    { name: "Comprehension and Summary", nameAfrikaans: "Begrip en Opsomming", capsCode: "ENGF-6" },
    { name: "Essay Writing", nameAfrikaans: "Opstelskryf", capsCode: "ENGF-7" },
    { name: "Transactional Writing", nameAfrikaans: "Transaksionele Skryf", capsCode: "ENGF-8" },
  ],
  AFRH: [
    { name: "Letterkunde: Roman", nameAfrikaans: "Letterkunde: Roman", capsCode: "AFRH-1" },
    { name: "Letterkunde: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "AFRH-2" },
    { name: "Letterkunde: Poësie", nameAfrikaans: "Letterkunde: Poësie", capsCode: "AFRH-3" },
    { name: "Letterkunde: Kortverhale", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "AFRH-4" },
    { name: "Taalstrukture en Konvensies", nameAfrikaans: "Taalstrukture en Konvensies", capsCode: "AFRH-5" },
    { name: "Begrip en Opsomming", nameAfrikaans: "Begrip en Opsomming", capsCode: "AFRH-6" },
    { name: "Opstelskryf", nameAfrikaans: "Opstelskryf", capsCode: "AFRH-7" },
    { name: "Transaksionele Skryf", nameAfrikaans: "Transaksionele Skryf", capsCode: "AFRH-8" },
  ],
  AFRF: [
    { name: "Letterkunde: Roman", nameAfrikaans: "Letterkunde: Roman", capsCode: "AFRF-1" },
    { name: "Letterkunde: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "AFRF-2" },
    { name: "Letterkunde: Poësie", nameAfrikaans: "Letterkunde: Poësie", capsCode: "AFRF-3" },
    { name: "Letterkunde: Kortverhale", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "AFRF-4" },
    { name: "Taalstrukture en Konvensies", nameAfrikaans: "Taalstrukture en Konvensies", capsCode: "AFRF-5" },
    { name: "Begrip en Opsomming", nameAfrikaans: "Begrip en Opsomming", capsCode: "AFRF-6" },
    { name: "Opstelskryf", nameAfrikaans: "Opstelskryf", capsCode: "AFRF-7" },
    { name: "Transaksionele Skryf", nameAfrikaans: "Transaksionele Skryf", capsCode: "AFRF-8" },
  ],
  IT: [
    { name: "Solution Development", nameAfrikaans: "Oplossings-ontwikkeling", capsCode: "IT-1" },
    { name: "Data and Information Management", nameAfrikaans: "Data- en Inligtingsbestuur", capsCode: "IT-2" },
    { name: "System Technologies", nameAfrikaans: "Stelseltegnologieë", capsCode: "IT-3" },
    { name: "Internet Technologies", nameAfrikaans: "Internettegnologieë", capsCode: "IT-4" },
    { name: "Object-Oriented Programming", nameAfrikaans: "Objekgeoriënteerde Programmering", capsCode: "IT-5" },
    { name: "Problem-Solving", nameAfrikaans: "Probleemoplossing", capsCode: "IT-6" },
  ],
  CAT: [
    { name: "Solution Development", nameAfrikaans: "Oplossings-ontwikkeling", capsCode: "CAT-1" },
    { name: "System Technologies", nameAfrikaans: "Stelseltegnologieë", capsCode: "CAT-2" },
    { name: "Internet Technologies", nameAfrikaans: "Internettegnologieë", capsCode: "CAT-3" },
    { name: "Information Management", nameAfrikaans: "Inligtingsbestuur", capsCode: "CAT-4" },
    { name: "Spreadsheets", nameAfrikaans: "Sigblaaie", capsCode: "CAT-5" },
    { name: "Database", nameAfrikaans: "Databasis", capsCode: "CAT-6" },
    { name: "Word Processing", nameAfrikaans: "Woordverwerking", capsCode: "CAT-7" },
  ],
  EGD: [
    { name: "Civil Drawing", nameAfrikaans: "Siviele Tekening", capsCode: "EGD-1" },
    { name: "Mechanical Drawing", nameAfrikaans: "Meganiese Tekening", capsCode: "EGD-2" },
    { name: "Isometric Drawing", nameAfrikaans: "Isometriese Tekening", capsCode: "EGD-3" },
    { name: "Perspective Drawing", nameAfrikaans: "Perspektieftekening", capsCode: "EGD-4" },
    { name: "Interpenetration and Development", nameAfrikaans: "Interpenetrasie en Ontwikkeling", capsCode: "EGD-5" },
    { name: "Loci of Points", nameAfrikaans: "Lokus van Punte", capsCode: "EGD-6" },
  ],
  AGR: [
    { name: "Agricultural Management", nameAfrikaans: "Landboubestuur", capsCode: "AGR-1" },
    { name: "Animal Production", nameAfrikaans: "Diereproduksie", capsCode: "AGR-2" },
    { name: "Animal Nutrition", nameAfrikaans: "Dierevoeding", capsCode: "AGR-3" },
    { name: "Animal Reproduction", nameAfrikaans: "Dierevoortplanting", capsCode: "AGR-4" },
    { name: "Plant Production", nameAfrikaans: "Plantproduksie", capsCode: "AGR-5" },
    { name: "Soil Science", nameAfrikaans: "Grondwetenskap", capsCode: "AGR-6" },
    { name: "Agricultural Economics", nameAfrikaans: "Landbou-ekonomie", capsCode: "AGR-7" },
  ],
  CON: [
    { name: "The Consumer", nameAfrikaans: "Die Verbruiker", capsCode: "CON-1" },
    { name: "Food and Nutrition", nameAfrikaans: "Voedsel en Voeding", capsCode: "CON-2" },
    { name: "Clothing", nameAfrikaans: "Kleding", capsCode: "CON-3" },
    { name: "Housing and Interior", nameAfrikaans: "Behuising en Interieur", capsCode: "CON-4" },
    { name: "Entrepreneurship", nameAfrikaans: "Entrepreneurskap", capsCode: "CON-5" },
  ],
  TOUR: [
    { name: "Tourism Sectors", nameAfrikaans: "Toerismesektore", capsCode: "TOUR-1" },
    { name: "Sustainable Tourism", nameAfrikaans: "Volhoubare Toerisme", capsCode: "TOUR-2" },
    { name: "Marketing", nameAfrikaans: "Bemarking", capsCode: "TOUR-3" },
    { name: "Tourism Geography", nameAfrikaans: "Toerisme-geografie", capsCode: "TOUR-4" },
    { name: "Customer Care", nameAfrikaans: "Kliëntediens", capsCode: "TOUR-5" },
    { name: "Foreign Exchange", nameAfrikaans: "Buitelandse Valuta", capsCode: "TOUR-6" },
    { name: "Map Skills", nameAfrikaans: "Kaartvaardighede", capsCode: "TOUR-7" },
  ],
  ART: [
    { name: "Visual Culture Studies", nameAfrikaans: "Visuele Kultuurstudie", capsCode: "ART-1" },
    { name: "Visual Arts in Context", nameAfrikaans: "Visuele Kunste in Konteks", capsCode: "ART-2" },
    { name: "Art Making and Design", nameAfrikaans: "Kunsmaak en Ontwerp", capsCode: "ART-3" },
    { name: "Contemporary Art", nameAfrikaans: "Kontemporêre Kuns", capsCode: "ART-4" },
    { name: "South African Art", nameAfrikaans: "Suid-Afrikaanse Kuns", capsCode: "ART-5" },
  ],
  TMATH: [
    { name: "Number Patterns, Sequences and Series", nameAfrikaans: "Getalpatrone, Rye en Reekse", capsCode: "TMATH-1" },
    { name: "Functions and Graphs", nameAfrikaans: "Funksies en Grafieke", capsCode: "TMATH-2" },
    { name: "Finance, Growth and Decay", nameAfrikaans: "Finansies, Groei en Verval", capsCode: "TMATH-3" },
    { name: "Trigonometry", nameAfrikaans: "Trigonometrie", capsCode: "TMATH-4" },
    { name: "Euclidean Geometry", nameAfrikaans: "Euklidiese Meetkunde", capsCode: "TMATH-5" },
    { name: "Mensuration", nameAfrikaans: "Meting", capsCode: "TMATH-6" },
    { name: "Statistics and Regression", nameAfrikaans: "Statistiek en Regressie", capsCode: "TMATH-7" },
    { name: "Probability", nameAfrikaans: "Waarskynlikheid", capsCode: "TMATH-8" },
  ],
  TSCI: [
    { name: "Mechanics", nameAfrikaans: "Meganika", capsCode: "TSCI-1" },
    { name: "Waves, Sound and Light", nameAfrikaans: "Golwe, Klank en Lig", capsCode: "TSCI-2" },
    { name: "Electricity and Magnetism", nameAfrikaans: "Elektrisiteit en Magnetisme", capsCode: "TSCI-3" },
    { name: "Matter and Materials", nameAfrikaans: "Materie en Materiale", capsCode: "TSCI-4" },
    { name: "Chemical Change", nameAfrikaans: "Chemiese Verandering", capsCode: "TSCI-5" },
    { name: "Applied Technology", nameAfrikaans: "Toegepaste Tegnologie", capsCode: "TSCI-6" },
  ],
  RELI: [
    { name: "Religion and Belief", nameAfrikaans: "Godsdiens en Geloof", capsCode: "RELI-1" },
    { name: "Religious Ethics", nameAfrikaans: "Godsdienstige Etiek", capsCode: "RELI-2" },
    { name: "World Religions", nameAfrikaans: "Wêreldgodsdienste", capsCode: "RELI-3" },
    { name: "Religion and Society", nameAfrikaans: "Godsdiens en Samelewing", capsCode: "RELI-4" },
    { name: "South African Religions", nameAfrikaans: "Suid-Afrikaanse Godsdienste", capsCode: "RELI-5" },
  ],
  DRAMA: [
    { name: "Drama Theory and History", nameAfrikaans: "Dramateorie en -Geskiedenis", capsCode: "DRAMA-1" },
    { name: "Acting and Performance", nameAfrikaans: "Speel en Uitvoering", capsCode: "DRAMA-2" },
    { name: "Devising and Playwriting", nameAfrikaans: "Skep en Toneelskryf", capsCode: "DRAMA-3" },
    { name: "Technical Theatre", nameAfrikaans: "Tegniese Teater", capsCode: "DRAMA-4" },
    { name: "South African Drama", nameAfrikaans: "Suid-Afrikaanse Drama", capsCode: "DRAMA-5" },
  ],
  DANCE: [
    { name: "Dance Theory and History", nameAfrikaans: "Dansteorie en -Geskiedenis", capsCode: "DANCE-1" },
    { name: "African Dance Forms", nameAfrikaans: "Afrikadansvorms", capsCode: "DANCE-2" },
    { name: "Classical Forms", nameAfrikaans: "Klassieke Vorms", capsCode: "DANCE-3" },
    { name: "Contemporary Dance", nameAfrikaans: "Kontemporêre Dans", capsCode: "DANCE-4" },
    { name: "Choreography and Composition", nameAfrikaans: "Choreografie en Komposisie", capsCode: "DANCE-5" },
  ],
  MUSIC: [
    { name: "Music Theory and Harmony", nameAfrikaans: "Musiekteorie en Harmonie", capsCode: "MUSIC-1" },
    { name: "Music History and Appreciation", nameAfrikaans: "Musiekgeskiedenis en -Waardering", capsCode: "MUSIC-2" },
    { name: "Practical Performance", nameAfrikaans: "Praktiese Uitvoering", capsCode: "MUSIC-3" },
    { name: "African Music Traditions", nameAfrikaans: "Afrika-Musiek-tradisies", capsCode: "MUSIC-4" },
    { name: "Composition and Arranging", nameAfrikaans: "Komposisie en Arrangering", capsCode: "MUSIC-5" },
  ],
  DESIGN: [
    { name: "Design Principles and Elements", nameAfrikaans: "Ontwerpbeginsels en -Elemente", capsCode: "DESIGN-1" },
    { name: "Design History and Theory", nameAfrikaans: "Ontwerpgeskiedenis en -Teorie", capsCode: "DESIGN-2" },
    { name: "Communication Design", nameAfrikaans: "Kommunikasieontwerp", capsCode: "DESIGN-3" },
    { name: "Environmental and Industrial Design", nameAfrikaans: "Omgewing- en Industriële Ontwerp", capsCode: "DESIGN-4" },
    { name: "Surface Design and Fashion", nameAfrikaans: "Oppervlakontwerp en Mode", capsCode: "DESIGN-5" },
  ],
  CIVT: [
    { name: "Structures", nameAfrikaans: "Strukture", capsCode: "CIVT-1" },
    { name: "Construction Materials", nameAfrikaans: "Boumateriaal", capsCode: "CIVT-2" },
    { name: "Construction Processes", nameAfrikaans: "Boukonstruksieprosesse", capsCode: "CIVT-3" },
    { name: "Drawing and Design", nameAfrikaans: "Tekening en Ontwerp", capsCode: "CIVT-4" },
    { name: "Civil Services", nameAfrikaans: "Siviele Dienste", capsCode: "CIVT-5" },
  ],
  ELEC: [
    { name: "AC and DC Theory", nameAfrikaans: "WS en GS Teorie", capsCode: "ELEC-1" },
    { name: "Digital Electronics", nameAfrikaans: "Digitale Elektronika", capsCode: "ELEC-2" },
    { name: "Industrial Electronics", nameAfrikaans: "Industriële Elektronika", capsCode: "ELEC-3" },
    { name: "Power Systems", nameAfrikaans: "Kragstelsels", capsCode: "ELEC-4" },
    { name: "Motor Control", nameAfrikaans: "Motorbeheer", capsCode: "ELEC-5" },
  ],
  MECH: [
    { name: "Fitting and Machining", nameAfrikaans: "Passing en Bewerking", capsCode: "MECH-1" },
    { name: "Welding", nameAfrikaans: "Sweising", capsCode: "MECH-2" },
    { name: "Automotive", nameAfrikaans: "Motorvoertuig", capsCode: "MECH-3" },
    { name: "Plumbing", nameAfrikaans: "Loodgieterswerk", capsCode: "MECH-4" },
    { name: "Applied Mechanics", nameAfrikaans: "Toegepaste Meganika", capsCode: "MECH-5" },
  ],
  DIGT: [
    { name: "Digital Systems and Networks", nameAfrikaans: "Digitale Stelsels en Netwerke", capsCode: "DIGT-1" },
    { name: "Programming and Software Development", nameAfrikaans: "Programmering en Sagteware-ontwikkeling", capsCode: "DIGT-2" },
    { name: "Data Management and Databases", nameAfrikaans: "Databestuur en Databasisse", capsCode: "DIGT-3" },
    { name: "Cybersecurity", nameAfrikaans: "Kuberveiligheid", capsCode: "DIGT-4" },
    { name: "Digital Communication", nameAfrikaans: "Digitale Kommunikasie", capsCode: "DIGT-5" },
  ],
  AGRM: [
    { name: "Farm Management", nameAfrikaans: "Plaasbestuur", capsCode: "AGRM-1" },
    { name: "Agricultural Economics", nameAfrikaans: "Landbou-ekonomie", capsCode: "AGRM-2" },
    { name: "Marketing of Agricultural Products", nameAfrikaans: "Bemarking van Landbouprodukte", capsCode: "AGRM-3" },
    { name: "Soil Management", nameAfrikaans: "Grondbestuur", capsCode: "AGRM-4" },
    { name: "Water Management", nameAfrikaans: "Waterbestuur", capsCode: "AGRM-5" },
  ],
  AGRT: [
    { name: "Crop Production Technology", nameAfrikaans: "Gewasproduksietegnologie", capsCode: "AGRT-1" },
    { name: "Animal Production Technology", nameAfrikaans: "Dierlike Produksietegnologie", capsCode: "AGRT-2" },
    { name: "Agricultural Mechanisation", nameAfrikaans: "Landboumeganisasie", capsCode: "AGRT-3" },
    { name: "Irrigation Systems", nameAfrikaans: "Besproeiingstelsels", capsCode: "AGRT-4" },
    { name: "Precision Agriculture", nameAfrikaans: "Presisielandbou", capsCode: "AGRT-5" },
  ],
  HOSP: [
    { name: "Food Preparation and Cooking", nameAfrikaans: "Voedselvoorbereiding en Kook", capsCode: "HOSP-1" },
    { name: "Hospitality Services", nameAfrikaans: "Gasvryheidsdienste", capsCode: "HOSP-2" },
    { name: "Nutrition and Menu Planning", nameAfrikaans: "Voeding en Spyseniering", capsCode: "HOSP-3" },
    { name: "Accommodation Services", nameAfrikaans: "Akkommodasiedienste", capsCode: "HOSP-4" },
    { name: "Tourism and Hospitality Industry", nameAfrikaans: "Toerisme en Gasvryheidsnywerheid", capsCode: "HOSP-5" },
  ],
  LO: [
    { name: "Personal Development", nameAfrikaans: "Persoonlike Ontwikkeling", capsCode: "LO-1" },
    { name: "Citizenship Education and Democracy", nameAfrikaans: "Burgerskapopvoeding en Demokrasie", capsCode: "LO-2" },
    { name: "Career and Career Choices", nameAfrikaans: "Loopbaan en Loopbaankeuses", capsCode: "LO-3" },
    { name: "Physical Education and Recreational Activities", nameAfrikaans: "Liggaamlike Opvoeding en Rekreasie", capsCode: "LO-4" },
    { name: "Health and Environmental Responsibility", nameAfrikaans: "Gesondheid en Omgewingsverantwoordelikheid", capsCode: "LO-5" },
  ],

  // ---- African Official Languages — Home Language ----
  ZULH: [
    { name: "Literature: Novel", nameAfrikaans: "Letterkunde: Roman", capsCode: "ZULH-1" },
    { name: "Literature: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "ZULH-2" },
    { name: "Literature: Poetry", nameAfrikaans: "Letterkunde: Poësie", capsCode: "ZULH-3" },
    { name: "Literature: Short Stories", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "ZULH-4" },
    { name: "Language Structures and Conventions", nameAfrikaans: "Taalstrukture en Konvensies", capsCode: "ZULH-5" },
    { name: "Comprehension and Summary", nameAfrikaans: "Begrip en Opsomming", capsCode: "ZULH-6" },
    { name: "Essay Writing", nameAfrikaans: "Opstelskryf", capsCode: "ZULH-7" },
    { name: "Transactional Writing", nameAfrikaans: "Transaksionele Skryf", capsCode: "ZULH-8" },
  ],
  XHOH: [
    { name: "Literature: Novel", nameAfrikaans: "Letterkunde: Roman", capsCode: "XHOH-1" },
    { name: "Literature: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "XHOH-2" },
    { name: "Literature: Poetry", nameAfrikaans: "Letterkunde: Poësie", capsCode: "XHOH-3" },
    { name: "Literature: Short Stories", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "XHOH-4" },
    { name: "Language Structures and Conventions", nameAfrikaans: "Taalstrukture en Konvensies", capsCode: "XHOH-5" },
    { name: "Comprehension and Summary", nameAfrikaans: "Begrip en Opsomming", capsCode: "XHOH-6" },
    { name: "Essay Writing", nameAfrikaans: "Opstelskryf", capsCode: "XHOH-7" },
    { name: "Transactional Writing", nameAfrikaans: "Transaksionele Skryf", capsCode: "XHOH-8" },
  ],
  SEPH: [
    { name: "Literature: Novel", nameAfrikaans: "Letterkunde: Roman", capsCode: "SEPH-1" },
    { name: "Literature: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "SEPH-2" },
    { name: "Literature: Poetry", nameAfrikaans: "Letterkunde: Poësie", capsCode: "SEPH-3" },
    { name: "Literature: Short Stories", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "SEPH-4" },
    { name: "Language Structures and Conventions", nameAfrikaans: "Taalstrukture en Konvensies", capsCode: "SEPH-5" },
    { name: "Comprehension and Summary", nameAfrikaans: "Begrip en Opsomming", capsCode: "SEPH-6" },
    { name: "Essay Writing", nameAfrikaans: "Opstelskryf", capsCode: "SEPH-7" },
    { name: "Transactional Writing", nameAfrikaans: "Transaksionele Skryf", capsCode: "SEPH-8" },
  ],
  SETH: [
    { name: "Literature: Novel", nameAfrikaans: "Letterkunde: Roman", capsCode: "SETH-1" },
    { name: "Literature: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "SETH-2" },
    { name: "Literature: Poetry", nameAfrikaans: "Letterkunde: Poësie", capsCode: "SETH-3" },
    { name: "Literature: Short Stories", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "SETH-4" },
    { name: "Language Structures and Conventions", nameAfrikaans: "Taalstrukture en Konvensies", capsCode: "SETH-5" },
    { name: "Comprehension and Summary", nameAfrikaans: "Begrip en Opsomming", capsCode: "SETH-6" },
    { name: "Essay Writing", nameAfrikaans: "Opstelskryf", capsCode: "SETH-7" },
    { name: "Transactional Writing", nameAfrikaans: "Transaksionele Skryf", capsCode: "SETH-8" },
  ],
  SESH: [
    { name: "Literature: Novel", nameAfrikaans: "Letterkunde: Roman", capsCode: "SESH-1" },
    { name: "Literature: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "SESH-2" },
    { name: "Literature: Poetry", nameAfrikaans: "Letterkunde: Poësie", capsCode: "SESH-3" },
    { name: "Literature: Short Stories", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "SESH-4" },
    { name: "Language Structures and Conventions", nameAfrikaans: "Taalstrukture en Konvensies", capsCode: "SESH-5" },
    { name: "Comprehension and Summary", nameAfrikaans: "Begrip en Opsomming", capsCode: "SESH-6" },
    { name: "Essay Writing", nameAfrikaans: "Opstelskryf", capsCode: "SESH-7" },
    { name: "Transactional Writing", nameAfrikaans: "Transaksionele Skryf", capsCode: "SESH-8" },
  ],
  TSHH: [
    { name: "Literature: Novel", nameAfrikaans: "Letterkunde: Roman", capsCode: "TSHH-1" },
    { name: "Literature: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "TSHH-2" },
    { name: "Literature: Poetry", nameAfrikaans: "Letterkunde: Poësie", capsCode: "TSHH-3" },
    { name: "Literature: Short Stories", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "TSHH-4" },
    { name: "Language Structures and Conventions", nameAfrikaans: "Taalstrukture en Konvensies", capsCode: "TSHH-5" },
    { name: "Comprehension and Summary", nameAfrikaans: "Begrip en Opsomming", capsCode: "TSHH-6" },
    { name: "Essay Writing", nameAfrikaans: "Opstelskryf", capsCode: "TSHH-7" },
    { name: "Transactional Writing", nameAfrikaans: "Transaksionele Skryf", capsCode: "TSHH-8" },
  ],
  XITH: [
    { name: "Literature: Novel", nameAfrikaans: "Letterkunde: Roman", capsCode: "XITH-1" },
    { name: "Literature: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "XITH-2" },
    { name: "Literature: Poetry", nameAfrikaans: "Letterkunde: Poësie", capsCode: "XITH-3" },
    { name: "Literature: Short Stories", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "XITH-4" },
    { name: "Language Structures and Conventions", nameAfrikaans: "Taalstrukture en Konvensies", capsCode: "XITH-5" },
    { name: "Comprehension and Summary", nameAfrikaans: "Begrip en Opsomming", capsCode: "XITH-6" },
    { name: "Essay Writing", nameAfrikaans: "Opstelskryf", capsCode: "XITH-7" },
    { name: "Transactional Writing", nameAfrikaans: "Transaksionele Skryf", capsCode: "XITH-8" },
  ],
  NDH: [
    { name: "Literature: Novel", nameAfrikaans: "Letterkunde: Roman", capsCode: "NDH-1" },
    { name: "Literature: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "NDH-2" },
    { name: "Literature: Poetry", nameAfrikaans: "Letterkunde: Poësie", capsCode: "NDH-3" },
    { name: "Literature: Short Stories", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "NDH-4" },
    { name: "Language Structures and Conventions", nameAfrikaans: "Taalstrukture en Konvensies", capsCode: "NDH-5" },
    { name: "Comprehension and Summary", nameAfrikaans: "Begrip en Opsomming", capsCode: "NDH-6" },
    { name: "Essay Writing", nameAfrikaans: "Opstelskryf", capsCode: "NDH-7" },
    { name: "Transactional Writing", nameAfrikaans: "Transaksionele Skryf", capsCode: "NDH-8" },
  ],
  SWAH: [
    { name: "Literature: Novel", nameAfrikaans: "Letterkunde: Roman", capsCode: "SWAH-1" },
    { name: "Literature: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "SWAH-2" },
    { name: "Literature: Poetry", nameAfrikaans: "Letterkunde: Poësie", capsCode: "SWAH-3" },
    { name: "Literature: Short Stories", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "SWAH-4" },
    { name: "Language Structures and Conventions", nameAfrikaans: "Taalstrukture en Konvensies", capsCode: "SWAH-5" },
    { name: "Comprehension and Summary", nameAfrikaans: "Begrip en Opsomming", capsCode: "SWAH-6" },
    { name: "Essay Writing", nameAfrikaans: "Opstelskryf", capsCode: "SWAH-7" },
    { name: "Transactional Writing", nameAfrikaans: "Transaksionele Skryf", capsCode: "SWAH-8" },
  ],

  // ---- African Official Languages — First Additional Language ----
  ZULF: [
    { name: "Literature: Novel", nameAfrikaans: "Letterkunde: Roman", capsCode: "ZULF-1" },
    { name: "Literature: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "ZULF-2" },
    { name: "Literature: Poetry", nameAfrikaans: "Letterkunde: Poësie", capsCode: "ZULF-3" },
    { name: "Literature: Short Stories", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "ZULF-4" },
    { name: "Language Structures and Conventions", nameAfrikaans: "Taalstrukture en Konvensies", capsCode: "ZULF-5" },
    { name: "Comprehension and Summary", nameAfrikaans: "Begrip en Opsomming", capsCode: "ZULF-6" },
    { name: "Essay Writing", nameAfrikaans: "Opstelskryf", capsCode: "ZULF-7" },
    { name: "Transactional Writing", nameAfrikaans: "Transaksionele Skryf", capsCode: "ZULF-8" },
  ],
  XHOF: [
    { name: "Literature: Novel", nameAfrikaans: "Letterkunde: Roman", capsCode: "XHOF-1" },
    { name: "Literature: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "XHOF-2" },
    { name: "Literature: Poetry", nameAfrikaans: "Letterkunde: Poësie", capsCode: "XHOF-3" },
    { name: "Literature: Short Stories", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "XHOF-4" },
    { name: "Language Structures and Conventions", nameAfrikaans: "Taalstrukture en Konvensies", capsCode: "XHOF-5" },
    { name: "Comprehension and Summary", nameAfrikaans: "Begrip en Opsomming", capsCode: "XHOF-6" },
    { name: "Essay Writing", nameAfrikaans: "Opstelskryf", capsCode: "XHOF-7" },
    { name: "Transactional Writing", nameAfrikaans: "Transaksionele Skryf", capsCode: "XHOF-8" },
  ],
  SEPF: [
    { name: "Literature: Novel", nameAfrikaans: "Letterkunde: Roman", capsCode: "SEPF-1" },
    { name: "Literature: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "SEPF-2" },
    { name: "Literature: Poetry", nameAfrikaans: "Letterkunde: Poësie", capsCode: "SEPF-3" },
    { name: "Literature: Short Stories", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "SEPF-4" },
    { name: "Language Structures and Conventions", nameAfrikaans: "Taalstrukture en Konvensies", capsCode: "SEPF-5" },
    { name: "Comprehension and Summary", nameAfrikaans: "Begrip en Opsomming", capsCode: "SEPF-6" },
    { name: "Essay Writing", nameAfrikaans: "Opstelskryf", capsCode: "SEPF-7" },
    { name: "Transactional Writing", nameAfrikaans: "Transaksionele Skryf", capsCode: "SEPF-8" },
  ],
  SETF: [
    { name: "Literature: Novel", nameAfrikaans: "Letterkunde: Roman", capsCode: "SETF-1" },
    { name: "Literature: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "SETF-2" },
    { name: "Literature: Poetry", nameAfrikaans: "Letterkunde: Poësie", capsCode: "SETF-3" },
    { name: "Literature: Short Stories", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "SETF-4" },
    { name: "Language Structures and Conventions", nameAfrikaans: "Taalstrukture en Konvensies", capsCode: "SETF-5" },
    { name: "Comprehension and Summary", nameAfrikaans: "Begrip en Opsomming", capsCode: "SETF-6" },
    { name: "Essay Writing", nameAfrikaans: "Opstelskryf", capsCode: "SETF-7" },
    { name: "Transactional Writing", nameAfrikaans: "Transaksionele Skryf", capsCode: "SETF-8" },
  ],
  SESF: [
    { name: "Literature: Novel", nameAfrikaans: "Letterkunde: Roman", capsCode: "SESF-1" },
    { name: "Literature: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "SESF-2" },
    { name: "Literature: Poetry", nameAfrikaans: "Letterkunde: Poësie", capsCode: "SESF-3" },
    { name: "Literature: Short Stories", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "SESF-4" },
    { name: "Language Structures and Conventions", nameAfrikaans: "Taalstrukture en Konvensies", capsCode: "SESF-5" },
    { name: "Comprehension and Summary", nameAfrikaans: "Begrip en Opsomming", capsCode: "SESF-6" },
    { name: "Essay Writing", nameAfrikaans: "Opstelskryf", capsCode: "SESF-7" },
    { name: "Transactional Writing", nameAfrikaans: "Transaksionele Skryf", capsCode: "SESF-8" },
  ],
  TSHF: [
    { name: "Literature: Novel", nameAfrikaans: "Letterkunde: Roman", capsCode: "TSHF-1" },
    { name: "Literature: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "TSHF-2" },
    { name: "Literature: Poetry", nameAfrikaans: "Letterkunde: Poësie", capsCode: "TSHF-3" },
    { name: "Literature: Short Stories", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "TSHF-4" },
    { name: "Language Structures and Conventions", nameAfrikaans: "Taalstrukture en Konvensies", capsCode: "TSHF-5" },
    { name: "Comprehension and Summary", nameAfrikaans: "Begrip en Opsomming", capsCode: "TSHF-6" },
    { name: "Essay Writing", nameAfrikaans: "Opstelskryf", capsCode: "TSHF-7" },
    { name: "Transactional Writing", nameAfrikaans: "Transaksionele Skryf", capsCode: "TSHF-8" },
  ],
  XITF: [
    { name: "Literature: Novel", nameAfrikaans: "Letterkunde: Roman", capsCode: "XITF-1" },
    { name: "Literature: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "XITF-2" },
    { name: "Literature: Poetry", nameAfrikaans: "Letterkunde: Poësie", capsCode: "XITF-3" },
    { name: "Literature: Short Stories", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "XITF-4" },
    { name: "Language Structures and Conventions", nameAfrikaans: "Taalstrukture en Konvensies", capsCode: "XITF-5" },
    { name: "Comprehension and Summary", nameAfrikaans: "Begrip en Opsomming", capsCode: "XITF-6" },
    { name: "Essay Writing", nameAfrikaans: "Opstelskryf", capsCode: "XITF-7" },
    { name: "Transactional Writing", nameAfrikaans: "Transaksionele Skryf", capsCode: "XITF-8" },
  ],
  NDF: [
    { name: "Literature: Novel", nameAfrikaans: "Letterkunde: Roman", capsCode: "NDF-1" },
    { name: "Literature: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "NDF-2" },
    { name: "Literature: Poetry", nameAfrikaans: "Letterkunde: Poësie", capsCode: "NDF-3" },
    { name: "Literature: Short Stories", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "NDF-4" },
    { name: "Language Structures and Conventions", nameAfrikaans: "Taalstrukture en Konvensies", capsCode: "NDF-5" },
    { name: "Comprehension and Summary", nameAfrikaans: "Begrip en Opsomming", capsCode: "NDF-6" },
    { name: "Essay Writing", nameAfrikaans: "Opstelskryf", capsCode: "NDF-7" },
    { name: "Transactional Writing", nameAfrikaans: "Transaksionele Skryf", capsCode: "NDF-8" },
  ],
  SWAF: [
    { name: "Literature: Novel", nameAfrikaans: "Letterkunde: Roman", capsCode: "SWAF-1" },
    { name: "Literature: Drama", nameAfrikaans: "Letterkunde: Drama", capsCode: "SWAF-2" },
    { name: "Literature: Poetry", nameAfrikaans: "Letterkunde: Poësie", capsCode: "SWAF-3" },
    { name: "Literature: Short Stories", nameAfrikaans: "Letterkunde: Kortverhale", capsCode: "SWAF-4" },
    { name: "Language Structures and Conventions", nameAfrikaans: "Taalstrukture en Konvensies", capsCode: "SWAF-5" },
    { name: "Comprehension and Summary", nameAfrikaans: "Begrip en Opsomming", capsCode: "SWAF-6" },
    { name: "Essay Writing", nameAfrikaans: "Opstelskryf", capsCode: "SWAF-7" },
    { name: "Transactional Writing", nameAfrikaans: "Transaksionele Skryf", capsCode: "SWAF-8" },
  ],

  // ---- Marine Sciences ----
  MRSCI: [
    { name: "The Marine Environment and Ecosystems", nameAfrikaans: "Die Mariene Omgewing en Ekostelsels", capsCode: "MRSCI-1" },
    { name: "Ocean Physics and Chemistry", nameAfrikaans: "Oseanofisika en -chemie", capsCode: "MRSCI-2" },
    { name: "Marine Biology", nameAfrikaans: "Mariene Biologie", capsCode: "MRSCI-3" },
    { name: "Marine Resources and Conservation", nameAfrikaans: "Mariene Hulpbronne en Bewaring", capsCode: "MRSCI-4" },
    { name: "Climate Change and the Ocean", nameAfrikaans: "Klimaatsverandering en die Oseaan", capsCode: "MRSCI-5" },
  ],
};

// Learning Style Types based on onboarding answers
export type LearningStyle = "visual" | "auditory" | "reading" | "kinesthetic" | "mixed";

export const LEARNING_STYLE_INFO: Record<LearningStyle, { 
  name: string; 
  nameAfrikaans: string; 
  description: string;
  descriptionAfrikaans: string;
  tips: string[];
  tipsAfrikaans: string[];
}> = {
  mixed: {
    name: "Multimodal Learner",
    nameAfrikaans: "Veelsydige Leerder",
    description: "You learn well using a combination of different methods.",
    descriptionAfrikaans: "Jy leer goed as jy verskillende maniere kombineer — dit werk in jou guns!",
    tips: [
      "Mix different study techniques",
      "Use videos, notes, and practice together",
      "Find what works best for each subject",
      "Alternate between reading and doing",
    ],
    tipsAfrikaans: [
      "Meng verskillende studietegnieke saam",
      "Gebruik video's, notas én oefening in dieselfde sessie",
      "Vind wat vir elke vak die beste werk — een maat pas nie almal nie",
      "Wissel tussen lees en prakties doen",
    ],
  },
  visual: {
    name: "Visual Learner",
    nameAfrikaans: "Visuele Leerder",
    description: "You learn best through images, diagrams, and visual representations.",
    descriptionAfrikaans: "Jy verstaan goed as jy goed kan sien wat aangaan — diagramme en beelde is jou beste vriende.",
    tips: [
      "Use mind maps and diagrams",
      "Watch educational videos",
      "Color-code your notes",
      "Draw pictures to remember concepts",
    ],
    tipsAfrikaans: [
      "Gebruik breinkaarte en diagramme vir elke hoofstuk",
      "Kyk opvoedkundige YouTube-videos om konsepte vas te kry",
      "Kleurkodeer jou notas per onderwerp",
      "Teken jou eie sketse om idees te onthou",
    ],
  },
  auditory: {
    name: "Auditory Learner",
    nameAfrikaans: "Ouditiewe Leerder",
    description: "You learn best through listening and verbal explanations.",
    descriptionAfrikaans: "Jy snap goed as iemand dit verduidelik of as jy dit hardop hoor — jou ore is jou krag.",
    tips: [
      "Listen to podcasts and lectures",
      "Read notes aloud",
      "Discuss topics with study groups",
      "Record yourself explaining concepts",
    ],
    tipsAfrikaans: [
      "Luister na podkaste en aanlyn lesings terwyl jy ontspan",
      "Lees jou notas hardop — dit help dit insink",
      "Bespreek onderwerpe met vriende of 'n studiegroep",
      "Neem jouself op terwyl jy 'n konsep verduidelik — dan kan jy later terugluister",
    ],
  },
  reading: {
    name: "Reading/Writing Learner",
    nameAfrikaans: "Lees- en Skryfleerder",
    description: "You learn best through reading textbooks and taking notes.",
    descriptionAfrikaans: "Jy leer die beste deur te lees en te skryf — jou notas en handboeke is jou geheime wapen.",
    tips: [
      "Read textbooks thoroughly",
      "Rewrite notes in your own words",
      "Create summaries and lists",
      "Use flashcards with written content",
    ],
    tipsAfrikaans: [
      "Lees handboeke deeglik deur — moenie net vlak oor dit kyk nie",
      "Herskryf notas in jou eie woorde sodat dit sin maak",
      "Maak opsommings en lyste vir elke onderwerp",
      "Gebruik flitskaarte met geskrewe vrae en antwoorde",
    ],
  },
  kinesthetic: {
    name: "Kinesthetic Learner",
    nameAfrikaans: "Praktiese Leerder",
    description: "You learn best through hands-on practice and doing.",
    descriptionAfrikaans: "Jy leer die beste deur dit self te doen en te oefen — meer oefening beteken beter resultate vir jou.",
    tips: [
      "Practice lots of past papers",
      "Use physical objects to understand concepts",
      "Take breaks to move around",
      "Apply concepts to real-world examples",
    ],
    tipsAfrikaans: [
      "Doen soveel moontlik vorige vraestelle — dit is wat jou gereed maak",
      "Gebruik fisiese goed om konsepte te verstaan waar jy kan",
      "Neem gereeld pouses om te beweeg — jou brein werk beter daarna",
      "Pas wat jy leer toe op werklike voorbeelde om dit vas te kry",
    ],
  },
};

// Badge Definitions
export interface Badge {
  code: string;
  name: string;
  nameAfrikaans: string;
  description: string;
  descriptionAfrikaans: string;
  icon: string;
  color: string;
  requirement: string;
}

export const BADGES: Badge[] = [
  // Streak Badges
  {
    code: "streak_3",
    name: "Getting Started",
    nameAfrikaans: "Op Dreef",
    description: "Study for 3 days in a row",
    descriptionAfrikaans: "Studeer vir 3 dae agtereenvolgens",
    icon: "flame",
    color: "orange",
    requirement: "3_day_streak",
  },
  {
    code: "streak_7",
    name: "Week Warrior",
    nameAfrikaans: "Weekkampioen",
    description: "Study for 7 days in a row",
    descriptionAfrikaans: "Studeer vir 'n volle week sonder om 'n dag te mis",
    icon: "flame",
    color: "orange",
    requirement: "7_day_streak",
  },
  {
    code: "streak_14",
    name: "Two Week Champion",
    nameAfrikaans: "Twee Weke Sterk",
    description: "Study for 14 days in a row",
    descriptionAfrikaans: "Studeer vir 14 dae agtereenvolgens — dit vat toewyding!",
    icon: "flame",
    color: "red",
    requirement: "14_day_streak",
  },
  {
    code: "streak_30",
    name: "Monthly Master",
    nameAfrikaans: "Maandmeester",
    description: "Study for 30 days in a row",
    descriptionAfrikaans: "Studeer vir 'n volle maand sonder 'n dag oor te slaan",
    icon: "crown",
    color: "gold",
    requirement: "30_day_streak",
  },
  // Questions Badges
  {
    code: "questions_10",
    name: "First Steps",
    nameAfrikaans: "Eerste Tree",
    description: "Answer 10 questions",
    descriptionAfrikaans: "Beantwoord jou eerste 10 vrae",
    icon: "check",
    color: "green",
    requirement: "10_questions",
  },
  {
    code: "questions_50",
    name: "Getting Serious",
    nameAfrikaans: "In Erns",
    description: "Answer 50 questions",
    descriptionAfrikaans: "Beantwoord 50 vrae — jy meen dit!",
    icon: "check",
    color: "green",
    requirement: "50_questions",
  },
  {
    code: "questions_100",
    name: "Century Club",
    nameAfrikaans: "Honderd-klub",
    description: "Answer 100 questions",
    descriptionAfrikaans: "Beantwoord 100 vrae — dis 'n groot prestasie!",
    icon: "star",
    color: "blue",
    requirement: "100_questions",
  },
  {
    code: "questions_500",
    name: "Exam Ready",
    nameAfrikaans: "Eksamengereed",
    description: "Answer 500 questions",
    descriptionAfrikaans: "Beantwoord 500 vrae — jy is regtig gereed vir die eksamen",
    icon: "trophy",
    color: "cyan",
    requirement: "500_questions",
  },
  // Accuracy Badges
  {
    code: "accuracy_70",
    name: "Sharp Shooter",
    nameAfrikaans: "Skerp Skutter",
    description: "Achieve 70% accuracy",
    descriptionAfrikaans: "Kry 70% korrek — jy tref die kol!",
    icon: "target",
    color: "teal",
    requirement: "70_accuracy",
  },
  {
    code: "accuracy_80",
    name: "Precision Pro",
    nameAfrikaans: "Presisie Pro",
    description: "Achieve 80% accuracy",
    descriptionAfrikaans: "Kry 80% korrek — jy's op 'n hoë vlak!",
    icon: "target",
    color: "blue",
    requirement: "80_accuracy",
  },
  {
    code: "accuracy_90",
    name: "Distinction Material",
    nameAfrikaans: "Onderskeidingmateriaal",
    description: "Achieve 90% accuracy",
    descriptionAfrikaans: "Kry 90% korrek — dis onderskeidingsvlak, goed gedoen!",
    icon: "award",
    color: "gold",
    requirement: "90_accuracy",
  },
  // Subject Badges
  {
    code: "subject_mastery",
    name: "Subject Specialist",
    nameAfrikaans: "Vakspesialis",
    description: "Complete 50 questions in one subject",
    descriptionAfrikaans: "Voltooi 50 vrae in een vak — jy ken die werk!",
    icon: "book",
    color: "blue",
    requirement: "50_subject_questions",
  },
  // Exam Badges
  {
    code: "first_exam",
    name: "Exam Taker",
    nameAfrikaans: "Eksamenskrywer",
    description: "Complete your first Exam Ready session",
    descriptionAfrikaans: "Voltooi jou eerste Eksamengereed-sessie",
    icon: "shield",
    color: "amber",
    requirement: "first_exam_session",
  },
  {
    code: "exam_5",
    name: "Exam Veteran",
    nameAfrikaans: "Eksamenervare",
    description: "Complete 5 Exam Ready sessions",
    descriptionAfrikaans: "Voltooi 5 Eksamengereed-sessies — jy weet hoe om te oefen!",
    icon: "shield",
    color: "cyan",
    requirement: "5_exam_sessions",
  },
];

export const getBadgeByCode = (code: string): Badge | undefined => {
  return BADGES.find(b => b.code === code);
};
