// Daily Boost — one study tip + one Rizz motivational line per learner per day.
//
// GOAL: give every learner a small, cheerful nudge each morning that feels
//       written for them. Same pair all day, fresh pair tomorrow.
//
// DESIGN — WHY IT LOOKS LIKE THIS:
//
// 1. Determinism, not randomness. If a learner refreshes the dashboard the
//    tip and Rizz line must stay the same — otherwise it feels like the app
//    "changed its mind" mid-morning. We hash `${userId}:${sastDate}` and
//    index into the pool. Same key → same index → same content.
//
// 2. Free, instant, offline-safe. NEVER calls OpenAI. This endpoint sits on
//    the learner dashboard first paint — it cannot depend on a paid API being
//    up. The tip and Rizz pools are shipped in-code.
//
// 3. Bilingual pairs, not two separate lists. Every entry carries both `en`
//    and `af` copy on the same object, so the deterministic index picks the
//    SAME item regardless of the learner's language — an English learner and
//    an Afrikaans learner writing the same subject on the same day get the
//    same *content*, just in their language. Prevents drift between locales.
//
// 4. Tips have two sources, in this order:
//      (a) `subject_study_tips` filtered to the learner's selected subjects
//          — the per-subject examiner/exam tips generated by
//          content-generators.ts from real DBE material. Preferred when
//          available: those tips are grounded in the memos this learner will
//          actually write against.
//      (b) The in-code CURATED_TIPS fallback — 40+ generic exam-technique
//          tips that stay useful even when the DB tip table is empty (which
//          is the state on any fresh env, and today on prod for many
//          subjects). This is what makes the feature ship today.
//    The route logs which source it used so we can see coverage improve.
//
// 5. Rizz lines are always in-code. They're character voice, not exam
//    content — the DB tip generator has nothing to say about them.
//
// See tests/unit/daily-motivation.test.ts for the invariants this module
// promises: same day → same pair; different day → different pair; subject
// list actually filters the tip pool.

import { createHash } from "crypto";
import type { LangCode } from "./language";

// ─── Bilingual pair types ────────────────────────────────────────────────────

export interface BilingualTip {
  en: string;
  af: string;
  /** Optional subject tag — for curated fallback entries that lean on a
   *  specific subject. null means "works for any subject". */
  subject: string | null;
}

export interface BilingualRizz {
  en: string;
  af: string;
}

// ─── Curated fallback tip pool ───────────────────────────────────────────────
// 40+ Grade-12 study & exam-technique tips. Kept generic (or tagged to a
// broad subject family) so they apply even when we don't know which subjects
// the learner picked. Bilingual pairs so the same index resolves to the same
// idea in either language.
//
// Tone: practical, one action per tip, no filler. Assume the learner is
// already stressed — don't lecture, don't sugar-coat.
export const CURATED_TIPS: BilingualTip[] = [
  { subject: null, en: "Read every question twice before you answer — most lost marks come from misreading the command word.", af: "Lees elke vraag twee keer voor jy antwoord — die meeste marks gaan verlore omdat leerders die bevelwoord verkeerd lees." },
  { subject: null, en: "Match minutes to marks: a 10-mark question deserves about 10 minutes. Wear a watch and check it at every section break.", af: "Pas minute by marks aan: 'n 10-punt vraag verdien omtrent 10 minute. Dra 'n horlosie en kyk by elke afdelingsbreek." },
  { subject: null, en: "Do the questions you know first, then loop back to the hard ones. Momentum matters more than order.", af: "Doen eers die vrae wat jy ken, kom dan terug na die moeilikes. Momentum tel meer as volgorde." },
  { subject: null, en: "Underline the command word — Explain, Discuss, Evaluate, Calculate — before you write a single line. It tells you how many marks you're chasing.", af: "Onderstreep die bevelwoord — Verduidelik, Bespreek, Evalueer, Bereken — voor jy een lyn skryf. Dit sê vir jou hoeveel marks jy jaag." },
  { subject: null, en: "'Discuss' and 'Explain' each want at least two full sentences per mark. 'State' and 'Name' want one line.", af: "'Bespreek' en 'Verduidelik' wil elk ten minste twee volsinne per punt hê. 'Noem' en 'Meld' wil een lyn hê." },
  { subject: null, en: "Show every step in Paper 1 Maths — markers can only award method marks they can actually see on the page.", af: "Wys elke stap in Wiskunde Vraestel 1 — nasieners kan slegs metode-marks toeken wat hulle kan sien." },
  { subject: null, en: "For every essay, spend two minutes planning. A bad plan still beats no plan.", af: "Beplan twee minute voor elke opstel. 'n Swak plan is steeds beter as geen plan nie." },
  { subject: null, en: "Answer in the language you were taught in — switching mid-paper costs time and marks.", af: "Antwoord in die taal waarin jy onderrig is — mid-vraestel wissel kos tyd en marks." },
  { subject: null, en: "Sleep beats one more hour of cramming. Your brain files what you learned overnight.", af: "Slaap is meer werd as nog 'n uur van instampwerk. Jou brein liasseer oornag wat jy geleer het." },
  { subject: null, en: "Do one past paper timed, then mark yourself against the real memo. That's worth more than three untimed papers.", af: "Doen een oefenvraestel op tyd, merk dan jouself teen die regte memorandum. Dit is meer werd as drie sonder tydslimiet." },
  { subject: null, en: "If a formula is on the sheet, still write it out first — muscle memory beats freezing.", af: "As 'n formule op die blad is, skryf dit steeds eers uit — spiergeheue klop verstyf." },
  { subject: null, en: "Study in 45-minute blocks with 10-minute breaks. Any longer and your recall drops.", af: "Studeer in blokke van 45 minute met breuke van 10 minute. Langer, en jou herinnering daal." },
  { subject: null, en: "Teach a concept out loud to an empty chair. If you can't explain it, you don't know it yet.", af: "Verduidelik 'n konsep hardop vir 'n leë stoel. As jy dit nie kan verduidelik nie, ken jy dit nog nie." },
  { subject: null, en: "Rewrite messy notes into one page per topic. The rewrite IS the studying.", af: "Herskryf slordige notas as een bladsy per onderwerp. Die herskrywe IS die studie." },
  { subject: null, en: "Practise past paper questions from the last 5 years, not the last 15 — the syllabus shifts.", af: "Oefen vrae van die afgelope 5 jaar, nie die afgelope 15 nie — die kurrikulum verskuif." },
  { subject: null, en: "Highlight every 'compare', 'contrast' and 'in your view' — those are the marks essay markers hunt for.", af: "Merk elke 'vergelyk', 'kontrasteer' en 'volgens jou' — dis die marks waarna opstel-nasieners soek." },
  { subject: null, en: "Cross out mistakes with one line. Scribbles cost you paper marks — markers ignore anything crossed out clearly.", af: "Trek een lyn deur foute. Krabbels kos jou marks — nasieners ignoreer enigiets wat duidelik uitgekrap is." },
  { subject: null, en: "Number every answer to match the question — even sub-parts like 3.2.1. Miss a number and the marker skips it.", af: "Nommer elke antwoord om by die vraag te pas — selfs sub-dele soos 3.2.1. Mis 'n nommer en die nasiener slaan dit oor." },
  { subject: null, en: "Water and a light snack before the paper — sugar-heavy energy drinks spike then crash you.", af: "Water en 'n ligte peuselhappie voor die vraestel — energiedrankies vol suiker piek jou en laat jou dan sak." },
  { subject: null, en: "Read the WHOLE paper in the first 5 minutes. Know what's coming before you start writing.", af: "Lees die HELE vraestel in die eerste 5 minute. Weet wat kom voor jy begin skryf." },
  { subject: null, en: "In Physics and Maths, always write the units. A right number without units loses the last mark.", af: "In Fisika en Wiskunde, skryf altyd die eenhede. 'n Regte getal sonder eenhede verloor die laaste mark." },
  { subject: null, en: "Don't leave blanks — even a rough attempt can pick up a method mark. Blank = zero, always.", af: "Los niks oop nie — selfs 'n rowwe poging kan 'n metode-mark kry. Leeg = nul, altyd." },
  { subject: null, en: "Draw diagrams big enough to label. Small squished diagrams cost you labelling marks.", af: "Teken diagramme groot genoeg om te etiketteer. Klein gedrukte diagramme kos jou etiket-marks." },
  { subject: null, en: "For Business Studies, always answer in the exact format the memo uses — heading, then bullets, then explanation.", af: "Vir Besigheidstudies, antwoord altyd in die presiese formaat wat die memorandum gebruik — hoof, dan kolpunte, dan verduideliking." },
  { subject: null, en: "In Life Sciences, memorise the diagrams. Half the marks in Paper 1 come from labels.", af: "In Lewenswetenskappe, memoriseer die diagramme. Die helfte van die marks in Vraestel 1 kom van etikette af." },
  { subject: null, en: "For History source questions, always quote briefly from the source in your answer. 'The source states...' picks up a mark.", af: "Vir Geskiedenis-bronvrae, haal altyd kortliks uit die bron aan in jou antwoord. 'Die bron sê...' kry 'n mark." },
  { subject: null, en: "In English, always link back to the question in your final sentence. 'This shows that…' closes the loop.", af: "In Engels, verbind altyd terug na die vraag in jou laaste sin. 'Dit wys dat…' sluit die lus." },
  { subject: null, en: "Study active, not passive. Cover the page and try to write the answer from memory before you check.", af: "Studeer aktief, nie passief nie. Bedek die bladsy en probeer die antwoord uit geheue skryf voor jy nagaan." },
  { subject: null, en: "Two 25-minute focused sessions beat one distracted 90-minute session. Every time.", af: "Twee 25-minuut gefokusde sessies klop een afgeleide 90-minuut sessie. Elke keer." },
  { subject: null, en: "Put your phone in another room while you study. Face-down doesn't count.", af: "Sit jou foon in 'n ander kamer terwyl jy studeer. Op sy gesig neersit tel nie." },
  { subject: null, en: "Practise writing FAST. Legibly, but fast. The Grade 12 papers reward learners who can get all their thoughts down in time.", af: "Oefen om VINNIG te skryf. Leesbaar, maar vinnig. Graad 12-vraestelle beloon leerders wat al hul gedagtes betyds neerskryf." },
  { subject: null, en: "The night before: pack your bag, lay out your uniform, sleep by 22:00. Panic in the morning kills marks.", af: "Die aand vantevore: pak jou tas, lê jou uniform uit, slaap teen 22:00. Paniek in die oggend kos marks." },
  { subject: null, en: "For every past paper you finish, mark it and note the ONE topic you lost most marks on. Study THAT next.", af: "Vir elke oefenvraestel wat jy klaarmaak, merk dit en let op die EEN onderwerp waar jy die meeste marks verloor het. Studeer DAAI volgende." },
  { subject: null, en: "In Accounting, always show the full ledger format — dates, folios, amounts. Format marks add up.", af: "In Rekeningkunde, wys altyd die volle grootboek-formaat — datums, folio's, bedrae. Formaat-marks tel op." },
  { subject: null, en: "For Geography maps: use a ruler, always. Freehand distances lose you interpretation marks.", af: "Vir Aardrykskunde-kaarte: gebruik altyd 'n liniaal. Vry-hand afstande kos jou interpretasie-marks." },
  { subject: null, en: "In Afrikaans EAT, learn the 20 most-common idioms cold. They come up every year.", af: "In Afrikaans EAT, leer die 20 mees algemene idiome deeglik. Hulle kom elke jaar op." },
  { subject: null, en: "For Physical Sciences, memorise the definitions word-for-word. Markers accept only the CAPS wording.", af: "Vir Fisiese Wetenskappe, memoriseer die definisies woord-vir-woord. Nasieners aanvaar slegs die KABV-bewoording." },
  { subject: null, en: "Colour-code your notes: one colour per topic. Your eye finds the right page in half the time.", af: "Kleur-kodeer jou notas: een kleur per onderwerp. Jou oog vind die regte bladsy in die helfte van die tyd." },
  { subject: null, en: "Do the LAST question of the paper first if it's your strongest topic. Bank easy marks early.", af: "Doen die LAASTE vraag van die vraestel eerste as dit jou sterkste onderwerp is. Bank maklike marks vroeg." },
  { subject: null, en: "In multiple choice, cross out the two you know are wrong first. Even a guess between two is 50/50.", af: "In veelvuldige keuse, kruis eers die twee uit wat jy weet verkeerd is. Selfs 'n raai tussen twee is 50/50." },
  { subject: null, en: "For any 'in your opinion' question, always support it with a fact from the source. Opinion + evidence = full marks.", af: "Vir enige 'volgens jou mening'-vraag, ondersteun dit altyd met 'n feit uit die bron. Mening + bewys = volle marks." },
  { subject: null, en: "If you finish early, go back and check Question 1. That's where careless slips live.", af: "As jy vroeg klaar is, gaan terug en gaan Vraag 1 na. Dis waar slordige foute lê." },
  { subject: null, en: "Rest one full day per week. Burned-out brains don't retain what they read.", af: "Rus een volle dag per week. Uitgebrande breine onthou nie wat hulle lees nie." },
  { subject: null, en: "Talk to a classmate the day before the exam — not about the content, just about anything. Isolation feeds panic.", af: "Praat met 'n klasmaat die dag voor die eksamen — nie oor die inhoud nie, net oor enigiets. Isolasie voed paniek." },
];

// ─── Curated Rizz motivational lines ─────────────────────────────────────────
// 60+ short bilingual lines in Rizz's voice. Two sentences max, upbeat SA-teen
// voice, supportive senior — not clown. Never mocks, never fake-hyped, never
// makes promises the learner has to deliver on.
//
// The pool is intentionally wider than the tips: motivation gets stale faster
// than exam technique.
export const CURATED_RIZZ: BilingualRizz[] = [
  { en: "Yo. One page today is one page more than yesterday. Let's go.", af: "Yo. Een bladsy vandag is een bladsy meer as gister. Kom ons gaan." },
  { en: "You don't have to feel ready to start. Start anyway — ready shows up on the way.", af: "Jy hoef nie gereed te voel om te begin nie. Begin in elk geval — gereedheid wys homself op pad." },
  { en: "Small wins stack. One question. Then one more. Before you know it, you're through the topic.", af: "Klein oorwinnings stapel. Een vraag. Dan nog een. Voor jy weet, is jy deur die onderwerp." },
  { en: "You are further than you were on Monday. Give yourself credit for that before you open the book.", af: "Jy is verder as wat jy Maandag was. Erken dit vir jouself voor jy die boek oopmaak." },
  { en: "Matric isn't a sprint or a marathon. It's a stack of small daily choices. Make today's one.", af: "Matriek is nie 'n naelloop of marathon nie. Dis 'n stapel klein daaglikse keuses. Maak vandag s'n." },
  { en: "The learners who pass big aren't the smartest. They're the ones who showed up on the hard days.", af: "Die leerders wat groot slaag is nie die slimstes nie. Hulle is die wat op die swaar dae opgedaag het." },
  { en: "Feeling behind? Same as most of us. Doesn't change what today's job is.", af: "Voel agter? Dieselfde as die meeste van ons. Verander nie wat vandag se werk is nie." },
  { en: "I've seen your streak. Don't break it on the day you almost broke through.", af: "Ek het jou reeks gesien. Moenie dit breek op die dag wat jy amper deurgebreek het nie." },
  { en: "You don't need a perfect study set-up. You need to open the book. That's it.", af: "Jy het nie 'n perfekte studie-opstelling nodig nie. Jy moet die boek oopmaak. Dit is dit." },
  { en: "Your future self is watching this morning. Give them something to be proud of.", af: "Jou toekomstige self kyk vanoggend. Gee vir hulle iets om trots op te wees." },
  { en: "One past paper today. Not five. Just one, done properly. That's the play.", af: "Een oefenvraestel vandag. Nie vyf nie. Net een, behoorlik gedoen. Dis die plan." },
  { en: "Nervous means you care. That's a starting line, not a stop sign.", af: "Senuweeagtig beteken jy gee om. Dis 'n wegspring, nie 'n stopteken nie." },
  { en: "The topic you're avoiding is the topic that's costing you marks. Start there today.", af: "Die onderwerp wat jy vermy, is die onderwerp wat jou marks kos. Begin dáár vandag." },
  { en: "I've got your notes, I've got your progress, I've got you. Keep going.", af: "Ek het jou notas, ek het jou vordering, ek het jou. Hou aan." },
  { en: "Every question you get wrong now is one you won't get wrong in November.", af: "Elke vraag wat jy nou verkeerd kry, is een wat jy nie in November verkeerd sal kry nie." },
  { en: "Don't compare your Chapter 3 to someone else's Chapter 10. You're both writing the same paper.", af: "Moenie jou Hoofstuk 3 vergelyk met iemand anders se Hoofstuk 10 nie. Julle skryf dieselfde vraestel." },
  { en: "You've handled worse than this. Remember that when the exam room gets loud in your head.", af: "Jy het erger as hierdie hanteer. Onthou dit as die eksamenlokaal in jou kop lawaai raak." },
  { en: "Studying tired is fine. Studying while scrolling isn't. Put the phone down and just do 20 minutes.", af: "Moeg studeer is oukei. Studeer terwyl jy scroll is nie. Sit die foon neer en doen net 20 minute." },
  { en: "You don't have to love every subject. You have to write every subject. Fair is a myth — the pass isn't.", af: "Jy hoef nie elke vak lief te hê nie. Jy moet elke vak skryf. Regverdig is 'n mite — die slaag is nie." },
  { en: "One deep breath, one open book, one question. Repeat until momentum kicks in.", af: "Een diep asem, een oop boek, een vraag. Herhaal totdat momentum inskop." },
  { en: "The exam room can't scare you if the paper doesn't. Do enough papers and the room shrinks.", af: "Die eksamenlokaal kan jou nie skrik nie as die vraestel nie doen nie. Doen genoeg vraestelle en die lokaal krimp." },
  { en: "You are allowed to rest. You are not allowed to quit. Big difference.", af: "Jy mag rus. Jy mag nie ophou nie. Groot verskil." },
  { en: "Learners two years older than you passed on the same syllabus. You can too.", af: "Leerders twee jaar ouer as jy het op dieselfde sillabus geslaag. Jy kan ook." },
  { en: "Your best isn't your peak. It's what you gave today. Some days that's less. Still counts.", af: "Jou beste is nie jou hoogtepunt nie. Dis wat jy vandag gegee het. Party dae is dit minder. Tel steeds." },
  { en: "Grow bored of the topic. Boredom means you've seen it enough times to know it.", af: "Raak verveeld met die onderwerp. Verveeldheid beteken jy het dit genoeg gesien om dit te ken." },
  { en: "The paper doesn't know how you feel. It only knows what you wrote. Write.", af: "Die vraestel weet nie hoe jy voel nie. Dit weet net wat jy geskryf het. Skryf." },
  { en: "Confidence is a memory of past effort. Build the memory now.", af: "Selfvertroue is 'n herinnering aan vroeëre moeite. Bou die herinnering nou." },
  { en: "Every top achiever was once staring at a page they didn't understand. They just didn't close the book.", af: "Elke top-presteerder het eendag na 'n bladsy gestaar wat hulle nie verstaan het nie. Hulle het net nie die boek toegemaak nie." },
  { en: "You already know more than you're giving yourself credit for. Prove it with a past paper.", af: "Jy weet reeds meer as waarvoor jy jouself krediet gee. Bewys dit met 'n oefenvraestel." },
  { en: "Don't wait to feel motivated. Motivation shows up AFTER the first 10 minutes.", af: "Moenie wag om gemotiveerd te voel nie. Motivering wys op NA die eerste 10 minute." },
  { en: "One page. One question. One try. That's the whole formula.", af: "Een bladsy. Een vraag. Een probeerslag. Dis die hele formule." },
  { en: "The marker doesn't care how you feel today. They care what's on the page. Get it on the page.", af: "Die nasiener gee nie om hoe jy vandag voel nie. Hulle gee om wat op die bladsy is. Kry dit op die bladsy." },
  { en: "You are one good session away from feeling different about this whole thing.", af: "Jy is een goeie sessie ver van anders oor die hele ding te voel." },
  { en: "'I don't feel like it' is normal. 'I still did 20 minutes' is what passes matric.", af: "'Ek voel nie daarvoor nie' is normaal. 'Ek het steeds 20 minute gedoen' slaag matriek." },
  { en: "The paper you dread most is the paper you learn most from. Start it today.", af: "Die vraestel waarvoor jy die bangste is, is die een waarvan jy die meeste leer. Begin dit vandag." },
  { en: "Read one memo today. See how markers actually think. Then write like they read.", af: "Lees een memorandum vandag. Sien hoe nasieners werklik dink. Skryf dan soos hulle lees." },
  { en: "Every mistake you find at home is a mark you save in November. Hunt them down.", af: "Elke fout wat jy tuis vind, is 'n mark wat jy in November red. Jag hulle af." },
  { en: "Don't outrun your basics. If the definitions still trip you up, spend 15 minutes on them today.", af: "Moenie by jou basiese werk verby hardloop nie. As die definisies jou nog laat struikel, spandeer 15 minute daarop vandag." },
  { en: "You don't need 8 hours of study. You need 2 hours of real study. Real means phone-away, book-open.", af: "Jy het nie 8 uur van studie nodig nie. Jy het 2 uur van regte studie nodig. Regte beteken foon-weg, boek-oop." },
  { en: "Fifteen minutes now beats one hour tomorrow. Compound interest works on effort too.", af: "Vyftien minute nou klop een uur môre. Saamgestelde rente werk ook op moeite." },
  { en: "Perfectionism is procrastination in a suit. Draft the answer, then improve it.", af: "Perfeksionisme is uitstel in 'n pak. Skryf die antwoord, verbeter dit dan." },
  { en: "If you can teach it to a friend, you can write it in the exam. Find someone this week.", af: "As jy dit vir 'n vriend kan verduidelik, kan jy dit in die eksamen skryf. Vind iemand hierdie week." },
  { en: "You have never regretted a study session. You have regretted skipping one. Trust the pattern.", af: "Jy het nog nooit 'n studiesessie berou nie. Jy het al berou dat jy een oorgeslaan het. Vertrou die patroon." },
  { en: "November is closer than September was. Which means today matters MORE than yesterday did.", af: "November is nader as September was. Wat beteken vandag tel MEER as gister." },
  { en: "You are the only one who knows if you tried today. Let the answer be yes.", af: "Jy is die enigste een wat weet of jy vandag probeer het. Laat die antwoord 'ja' wees." },
  { en: "Don't study to feel busy. Study to feel confident. There's a difference.", af: "Moenie studeer om besig te voel nie. Studeer om selfversekerd te voel. Daar's 'n verskil." },
  { en: "The clock is only your enemy if you didn't practise against it. Time yourself today.", af: "Die horlosie is net jou vyand as jy nie daarteen geoefen het nie. Neem tyd vandag." },
  { en: "You already survived the hardest year of school. That was Grade 11. Take the confidence into today.", af: "Jy het reeds die moeilikste jaar van skool oorleef. Dit was Graad 11. Neem die vertroue vandag saam." },
  { en: "Rewrite the topic in your own words. If you can't, you don't know it — but now you know what to fix.", af: "Herskryf die onderwerp in jou eie woorde. As jy nie kan nie, ken jy dit nie — maar nou weet jy wat om reg te maak." },
  { en: "One good hour beats three broken hours. Close the tabs. Open the book. Timer on.", af: "Een goeie uur klop drie gebroke ure. Maak die oortjies toe. Maak die boek oop. Tydhouer aan." },
  { en: "Nobody has ever failed matric because they revised too much. But plenty pass because they revised at all.", af: "Niemand het al matriek gedruip omdat hulle te veel hersien het nie. Maar baie slaag omdat hulle glad hersien het." },
  { en: "The subject you find hardest gets easier at exactly the point most learners give up. Don't be most learners.", af: "Die vak wat jy die moeilikste vind, raak makliker presies op die punt wat die meeste leerders opgee. Moenie die meeste leerders wees nie." },
  { en: "Your notes don't need to be pretty. They need to work. Function before aesthetic.", af: "Jou notas hoef nie mooi te wees nie. Hulle moet werk. Funksie voor estetika." },
  { en: "You get to choose one thing today: study, or feel guilty for not studying. One takes less energy.", af: "Jy kies een ding vandag: studeer, of voel skuldig omdat jy nie studeer nie. Een neem minder energie." },
  { en: "The version of you writing the finals will thank the version of you sitting down right now.", af: "Die weergawe van jou wat die finale skryf, sal die weergawe van jou wat nou sit, bedank." },
  { en: "You wouldn't quit a game on level 11. Don't quit matric on Term 3.", af: "Jy sou nie 'n speletjie op vlak 11 los nie. Moenie matriek in Kwartaal 3 los nie." },
  { en: "Everything you learn this term becomes automatic by November. That's how brains work — trust it.", af: "Alles wat jy hierdie kwartaal leer, word teen November outomaties. So werk breine — vertrou dit." },
  { en: "Motivation gets you started. Systems keep you going. Set a fixed study slot today.", af: "Motivering laat jou begin. Sisteme hou jou aan die gang. Stel vandag 'n vaste studietyd." },
  { en: "You're allowed to have a bad day. Just don't have a bad week. Reset in the morning.", af: "Jy mag 'n slegte dag hê. Moenie net 'n slegte week hê nie. Herstel in die oggend." },
  { en: "One question at a time. That's how every past paper gets finished, and every matric gets passed.", af: "Een vraag op 'n slag. So word elke oefenvraestel voltooi, en elke matriek geslaag." },
  { en: "You already have everything you need to pass. What you need is to use it. Today.", af: "Jy het reeds alles wat jy nodig het om te slaag. Wat jy nodig het, is om dit te gebruik. Vandag." },
  { en: "Effort compounds. One session becomes a habit. One habit becomes a pass. Start.", af: "Moeite versnel. Een sessie word 'n gewoonte. Een gewoonte word 'n slag. Begin." },
  { en: "Nobody is coming to save your marks. But you don't need saving — you need one small win today.", af: "Niemand kom jou marks red nie. Maar jy het nie redding nodig nie — jy het een klein oorwinning vandag nodig." },
];

// ─── Selection ───────────────────────────────────────────────────────────────

/**
 * SAST date key ("YYYY-MM-DD") for a Date. Deterministic — a learner in Cape
 * Town at 01:00 sees the same key as one in Durban at 01:00, but a learner
 * refreshing at 00:15 rolls over to a fresh key because midnight is measured
 * in Johannesburg time, not UTC.
 *
 * en-CA is the shortest way to get the ISO YYYY-MM-DD format out of
 * toLocaleDateString without hand-rolling a formatter — matches the pattern
 * used elsewhere in routes.ts (see the activity aggregation there).
 */
export function sastDateKey(d: Date = new Date()): string {
  return d.toLocaleDateString("en-CA", { timeZone: "Africa/Johannesburg" });
}

/**
 * Deterministic non-negative integer from a string. sha256 → first 8 hex chars
 * → parseInt. Same input always yields the same output; changing either the
 * userId or the date changes it.
 *
 * We only need the first 8 hex chars (32 bits) because we mod into pools of
 * ≤ a few hundred items — collisions across those buckets are fine.
 */
export function dailyIndex(userId: string, sastKey: string, poolSize: number): number {
  if (poolSize <= 0) return 0;
  const h = createHash("sha256").update(`${userId}:${sastKey}`).digest("hex").slice(0, 8);
  const n = parseInt(h, 16);
  return n % poolSize;
}

/**
 * Pick today's Rizz motivational line for this learner. Always draws from the
 * in-code CURATED_RIZZ pool.
 */
export function pickDailyRizz(userId: string, sastKey: string): BilingualRizz {
  const idx = dailyIndex(`rizz:${userId}`, sastKey, CURATED_RIZZ.length);
  return CURATED_RIZZ[idx];
}

/**
 * Pick today's tip. If `subjectPool` has entries (from subject_study_tips
 * filtered to the learner's subjects) use it; otherwise fall back to
 * CURATED_TIPS. The prefix on the hash namespaces tips separately from Rizz,
 * so a learner can get both without them being suspiciously correlated.
 */
export function pickDailyTip<T>(
  userId: string,
  sastKey: string,
  subjectPool: T[],
  fallbackPool: T[],
): T {
  const pool = subjectPool.length > 0 ? subjectPool : fallbackPool;
  const idx = dailyIndex(`tip:${userId}`, sastKey, pool.length);
  return pool[idx];
}

/** Language-aware tip shape returned to the client. */
export interface ClientTip {
  text: string;
  textAf: string;
  /** Subject the tip belongs to, or null for generic fallback tips. */
  subject: string | null;
}

/** Language-aware Rizz shape returned to the client. */
export interface ClientRizz {
  text: string;
  textAf: string;
}

export function toClientTip(t: BilingualTip): ClientTip {
  return { text: t.en, textAf: t.af, subject: t.subject };
}

export function toClientRizz(r: BilingualRizz): ClientRizz {
  return { text: r.en, textAf: r.af };
}
