// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/braintrack-paywall/Accessibility.tsx": () => import("../components/mockups/braintrack-paywall/Accessibility.tsx"),
  "./components/mockups/braintrack-paywall/Affordance.tsx": () => import("../components/mockups/braintrack-paywall/Affordance.tsx"),
  "./components/mockups/braintrack-paywall/Hierarchy.tsx": () => import("../components/mockups/braintrack-paywall/Hierarchy.tsx"),
  "./components/mockups/parent-report/Editorial.tsx": () => import("../components/mockups/parent-report/Editorial.tsx"),
  "./components/mockups/parent-report/Narrative.tsx": () => import("../components/mockups/parent-report/Narrative.tsx"),
  "./components/mockups/parent-report/NeonCockpit.tsx": () => import("../components/mockups/parent-report/NeonCockpit.tsx")
};
